// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: antimage/v1/control.proto

package antimagev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EnrollRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Single-use, 30 minute TTL, bound to one node.
	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	// The node's CSR. Its private key never leaves the host, and the panel
	// never sees it.
	CsrDer          []byte `protobuf:"bytes,2,opt,name=csr_der,json=csrDer,proto3" json:"csr_der,omitempty"`
	AgentVersion    string `protobuf:"bytes,3,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`
	ProtocolVersion uint32 `protobuf:"varint,4,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *EnrollRequest) Reset() {
	*x = EnrollRequest{}
	mi := &file_antimage_v1_control_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrollRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrollRequest) ProtoMessage() {}

func (x *EnrollRequest) ProtoReflect() protoreflect.Message {
	mi := &file_antimage_v1_control_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrollRequest.ProtoReflect.Descriptor instead.
func (*EnrollRequest) Descriptor() ([]byte, []int) {
	return file_antimage_v1_control_proto_rawDescGZIP(), []int{0}
}

func (x *EnrollRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *EnrollRequest) GetCsrDer() []byte {
	if x != nil {
		return x.CsrDer
	}
	return nil
}

func (x *EnrollRequest) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

func (x *EnrollRequest) GetProtocolVersion() uint32 {
	if x != nil {
		return x.ProtocolVersion
	}
	return 0
}

type EnrollResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Signed client certificate, CN = node id. The panel names the node; the
	// CSR's own subject is ignored so a node cannot name itself.
	CertDer []byte `protobuf:"bytes,1,opt,name=cert_der,json=certDer,proto3" json:"cert_der,omitempty"`
	// Panel CA, for verifying the panel on later connections.
	CaDer         []byte `protobuf:"bytes,2,opt,name=ca_der,json=caDer,proto3" json:"ca_der,omitempty"`
	NodeId        int64  `protobuf:"varint,3,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnrollResponse) Reset() {
	*x = EnrollResponse{}
	mi := &file_antimage_v1_control_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrollResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrollResponse) ProtoMessage() {}

func (x *EnrollResponse) ProtoReflect() protoreflect.Message {
	mi := &file_antimage_v1_control_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrollResponse.ProtoReflect.Descriptor instead.
func (*EnrollResponse) Descriptor() ([]byte, []int) {
	return file_antimage_v1_control_proto_rawDescGZIP(), []int{1}
}

func (x *EnrollResponse) GetCertDer() []byte {
	if x != nil {
		return x.CertDer
	}
	return nil
}

func (x *EnrollResponse) GetCaDer() []byte {
	if x != nil {
		return x.CaDer
	}
	return nil
}

func (x *EnrollResponse) GetNodeId() int64 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

type AgentMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*AgentMessage_Hello
	//	*AgentMessage_Heartbeat
	//	*AgentMessage_ApplyReport
	//	*AgentMessage_UsageReport
	Payload       isAgentMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentMessage) Reset() {
	*x = AgentMessage{}
	mi := &file_antimage_v1_control_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentMessage) ProtoMessage() {}

func (x *AgentMessage) ProtoReflect() protoreflect.Message {
	mi := &file_antimage_v1_control_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentMessage.ProtoReflect.Descriptor instead.
func (*AgentMessage) Descriptor() ([]byte, []int) {
	return file_antimage_v1_control_proto_rawDescGZIP(), []int{2}
}

func (x *AgentMessage) GetPayload() isAgentMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *AgentMessage) GetHello() *Hello {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_Hello); ok {
			return x.Hello
		}
	}
	return nil
}

func (x *AgentMessage) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *AgentMessage) GetApplyReport() *ApplyReport {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_ApplyReport); ok {
			return x.ApplyReport
		}
	}
	return nil
}

func (x *AgentMessage) GetUsageReport() *UsageReport {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_UsageReport); ok {
			return x.UsageReport
		}
	}
	return nil
}

type isAgentMessage_Payload interface {
	isAgentMessage_Payload()
}

type AgentMessage_Hello struct {
	Hello *Hello `protobuf:"bytes,1,opt,name=hello,proto3,oneof"`
}

type AgentMessage_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,2,opt,name=heartbeat,proto3,oneof"`
}

type AgentMessage_ApplyReport struct {
	ApplyReport *ApplyReport `protobuf:"bytes,3,opt,name=apply_report,json=applyReport,proto3,oneof"`
}

type AgentMessage_UsageReport struct {
	UsageReport *UsageReport `protobuf:"bytes,4,opt,name=usage_report,json=usageReport,proto3,oneof"`
}

func (*AgentMessage_Hello) isAgentMessage_Payload() {}

func (*AgentMessage_Heartbeat) isAgentMessage_Payload() {}

func (*AgentMessage_ApplyReport) isAgentMessage_Payload() {}

func (*AgentMessage_UsageReport) isAgentMessage_Payload() {}

type PanelMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*PanelMessage_RevisionBump
	//	*PanelMessage_FetchNow
	//	*PanelMessage_UpgradeRequired
	Payload       isPanelMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PanelMessage) Reset() {
	*x = PanelMessage{}
	mi := &file_antimage_v1_control_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PanelMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PanelMessage) ProtoMessage() {}

func (x *PanelMessage) ProtoReflect() protoreflect.Message {
	mi := &file_antimage_v1_control_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PanelMessage.ProtoReflect.Descriptor instead.
func (*PanelMessage) Descriptor() ([]byte, []int) {
	return file_antimage_v1_control_proto_rawDescGZIP(), []int{3}
}

func (x *PanelMessage) GetPayload() isPanelMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *PanelMessage) GetRevisionBump() *RevisionBump {
	if x != nil {
		if x, ok := x.Payload.(*PanelMessage_RevisionBump); ok {
			return x.RevisionBump
		}
	}
	return nil
}

func (x *PanelMessage) GetFetchNow() *FetchNow {
	if x != nil {
		if x, ok := x.Payload.(*PanelMessage_FetchNow); ok {
			return x.FetchNow
		}
	}
	return nil
}

func (x *PanelMessage) GetUpgradeRequired() *UpgradeRequired {
	if x != nil {
		if x, ok := x.Payload.(*PanelMessage_UpgradeRequired); ok {
			return x.UpgradeRequired
		}
	}
	return nil
}

type isPanelMessage_Payload interface {
	isPanelMessage_Payload()
}

type PanelMessage_RevisionBump struct {
	RevisionBump *RevisionBump `protobuf:"bytes,1,opt,name=revision_bump,json=revisionBump,proto3,oneof"`
}

type PanelMessage_FetchNow struct {
	FetchNow *FetchNow `protobuf:"bytes,2,opt,name=fetch_now,json=fetchNow,proto3,oneof"`
}

type PanelMessage_UpgradeRequired struct {
	UpgradeRequired *UpgradeRequired `protobuf:"bytes,3,opt,name=upgrade_required,json=upgradeRequired,proto3,oneof"`
}

func (*PanelMessage_RevisionBump) isPanelMessage_Payload() {}

func (*PanelMessage_FetchNow) isPanelMessage_Payload() {}

func (*PanelMessage_UpgradeRequired) isPanelMessage_Payload() {}

type Hello struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	NodeId          int64                  `protobuf:"varint,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	AgentVersion    string                 `protobuf:"bytes,2,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`
	ProtocolVersion uint32                 `protobuf:"varint,3,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	AppliedRevision int64                  `protobuf:"varint,4,opt,name=applied_revision,json=appliedRevision,proto3" json:"applied_revision,omitempty"`
	DocSha256       string                 `protobuf:"bytes,5,opt,name=doc_sha256,json=docSha256,proto3" json:"doc_sha256,omitempty"`
	Adapters        []*AdapterDescriptor   `protobuf:"bytes,6,rep,name=adapters,proto3" json:"adapters,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Hello) Reset() {
	*x = Hello{}
	mi := &file_antimage_v1_control_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hello) ProtoMessage() {}

func (x *Hello) ProtoReflect() protoreflect.Message {
	mi := &file_antimage_v1_control_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hello.ProtoReflect.Descriptor instead.
func (*Hello) Descriptor() ([]byte, []int) {
	return file_antimage_v1_control_proto_rawDescGZIP(), []int{4}
}

func (x *Hello) GetNodeId() int64 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

func (x *Hello) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

func (x *Hello) GetProtocolVersion() uint32 {
	if x != nil {
		return x.ProtocolVersion
	}
	return 0
}

func (x *Hello) GetAppliedRevision() int64 {
	if x != nil {
		return x.AppliedRevision
	}
	return 0
}

func (x *Hello) GetDocSha256() string {
	if x != nil {
		return x.DocSha256
	}
	return ""
}

func (x *Hello) GetAdapters() []*AdapterDescriptor {
	if x != nil {
		return x.Adapters
	}
	return nil
}

type AdapterDescriptor struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Kind           string                 `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	Version        string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	HotUserAdd     bool                   `protobuf:"varint,3,opt,name=hot_user_add,json=hotUserAdd,proto3" json:"hot_user_add,omitempty"`
	SelfAccounting bool                   `protobuf:"varint,4,opt,name=self_accounting,json=selfAccounting,proto3" json:"self_accounting,omitempty"`
	RequiresPki    bool                   `protobuf:"varint,5,opt,name=requires_pki,json=requiresPki,proto3" json:"requires_pki,omitempty"`
	// JSON Schema for this adapter's service params. The panel validates
	// writes against it and the UI renders forms from it.
	ServiceSchema []byte   `protobuf:"bytes,6,opt,name=service_schema,json=serviceSchema,proto3" json:"service_schema,omitempty"`
	Capabilities  []string `protobuf:"bytes,7,rep,name=capabilities,proto3" json:"capabilities,omitempty"` // SP5: adapter capabilities (e.g., ["tls", "ws", "grpc"])
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdapterDescriptor) Reset() {
	*x = AdapterDescriptor{}
	mi := &file_antimage_v1_control_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdapterDescriptor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdapterDescriptor) ProtoMessage() {}

func (x *AdapterDescriptor) ProtoReflect() protoreflect.Message {
	mi := &file_antimage_v1_control_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdapterDescriptor.ProtoReflect.Descriptor instead.
func (*AdapterDescriptor) Descriptor() ([]byte, []int) {
	return file_antimage_v1_control_proto_rawDescGZIP(), []int{5}
}

func (x *AdapterDescriptor) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *AdapterDescriptor) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *AdapterDescriptor) GetHotUserAdd() bool {
	if x != nil {
		return x.HotUserAdd
	}
	return false
}

func (x *AdapterDescriptor) GetSelfAccounting() bool {
	if x != nil {
		return x.SelfAccounting
	}
	return false
}

func (x *AdapterDescriptor) GetRequiresPki() bool {
	if x != nil {
		return x.RequiresPki
	}
	return false
}

func (x *AdapterDescriptor) GetServiceSchema() []byte {
	if x != nil {
		return x.ServiceSchema
	}
	return nil
}

func (x *AdapterDescriptor) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

type Heartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Load1         float64                `protobuf:"fixed64,1,opt,name=load1,proto3" json:"load1,omitempty"`
	MemUsedBytes  uint64                 `protobuf:"varint,2,opt,name=mem_used_bytes,json=memUsedBytes,proto3" json:"mem_used_bytes,omitempty"`
	UptimeSeconds uint64                 `protobuf:"varint,3,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	AdapterHealth []*AdapterHealth       `protobuf:"bytes,4,rep,name=adapter_health,json=adapterHealth,proto3" json:"adapter_health,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_antimage_v1_control_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_antimage_v1_control_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_antimage_v1_control_proto_rawDescGZIP(), []int{6}
}

func (x *Heartbeat) GetLoad1() float64 {
	if x != nil {
		return x.Load1
	}
	return 0
}

func (x *Heartbeat) GetMemUsedBytes() uint64 {
	if x != nil {
		return x.MemUsedBytes
	}
	return 0
}

func (x *Heartbeat) GetUptimeSeconds() uint64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

func (x *Heartbeat) GetAdapterHealth() []*AdapterHealth {
	if x != nil {
		return x.AdapterHealth
	}
	return nil
}

type AdapterHealth struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          string                 `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	Ok            bool                   `protobuf:"varint,2,opt,name=ok,proto3" json:"ok,omitempty"`
	Detail        string                 `protobuf:"bytes,3,opt,name=detail,proto3" json:"detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdapterHealth) Reset() {
	*x = AdapterHealth{}
	mi := &file_antimage_v1_control_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdapterHealth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdapterHealth) ProtoMessage() {}

func (x *AdapterHealth) ProtoReflect() protoreflect.Message {
	mi := &file_antimage_v1_control_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdapterHealth.ProtoReflect.Descriptor instead.
func (*AdapterHealth) Descriptor() ([]byte, []int) {
	return file_antimage_v1_control_proto_rawDescGZIP(), []int{7}
}

func (x *AdapterHealth) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *AdapterHealth) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *AdapterHealth) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

type ApplyReport struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TargetRevision int64                  `protobuf:"varint,1,opt,name=target_revision,json=targetRevision,proto3" json:"target_revision,omitempty"`
	Converged      bool                   `protobuf:"varint,2,opt,name=converged,proto3" json:"converged,omitempty"`
	Deferred       bool                   `protobuf:"varint,3,opt,name=deferred,proto3" json:"deferred,omitempty"`
	Error          string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	// The hash the agent actually applied. The panel compares this against the
	// hash it recorded for target_revision; a match on revision with a mismatch
	// here is an integrity fault, never convergence.
	DocSha256     string        `protobuf:"bytes,5,opt,name=doc_sha256,json=docSha256,proto3" json:"doc_sha256,omitempty"`
	Steps         []*StepResult `protobuf:"bytes,6,rep,name=steps,proto3" json:"steps,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyReport) Reset() {
	*x = ApplyReport{}
	mi := &file_antimage_v1_control_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyReport) ProtoMessage() {}

func (x *ApplyReport) ProtoReflect() protoreflect.Message {
	mi := &file_antimage_v1_control_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyReport.ProtoReflect.Descriptor instead.
func (*ApplyReport) Descriptor() ([]byte, []int) {
	return file_antimage_v1_control_proto_rawDescGZIP(), []int{8}
}

func (x *ApplyReport) GetTargetRevision() int64 {
	if x != nil {
		return x.TargetRevision
	}
	return 0
}

func (x *ApplyReport) GetConverged() bool {
	if x != nil {
		return x.Converged
	}
	return false
}

func (x *ApplyReport) GetDeferred() bool {
	if x != nil {
		return x.Deferred
	}
	return false
}

func (x *ApplyReport) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ApplyReport) GetDocSha256() string {
	if x != nil {
		return x.DocSha256
	}
	return ""
}

func (x *ApplyReport) GetSteps() []*StepResult {
	if x != nil {
		return x.Steps
	}
	return nil
}

type StepResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Seq   int32                  `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"`
	Kind  string                 `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	// "none" | "reload" | "restart"
	Disruption    string `protobuf:"bytes,3,opt,name=disruption,proto3" json:"disruption,omitempty"`
	Ok            bool   `protobuf:"varint,4,opt,name=ok,proto3" json:"ok,omitempty"`
	Error         string `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	DurationMs    int64  `protobuf:"varint,6,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StepResult) Reset() {
	*x = StepResult{}
	mi := &file_antimage_v1_control_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StepResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StepResult) ProtoMessage() {}

func (x *StepResult) ProtoReflect() protoreflect.Message {
	mi := &file_antimage_v1_control_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StepResult.ProtoReflect.Descriptor instead.
func (*StepResult) Descriptor() ([]byte, []int) {
	return file_antimage_v1_control_proto_rawDescGZIP(), []int{9}
}

func (x *StepResult) GetSeq() int32 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *StepResult) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *StepResult) GetDisruption() string {
	if x != nil {
		return x.Disruption
	}
	return ""
}

func (x *StepResult) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *StepResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *StepResult) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

type RevisionBump struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Revision      int64                  `protobuf:"varint,1,opt,name=revision,proto3" json:"revision,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevisionBump) Reset() {
	*x = RevisionBump{}
	mi := &file_antimage_v1_control_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevisionBump) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevisionBump) ProtoMessage() {}

func (x *RevisionBump) ProtoReflect() protoreflect.Message {
	mi := &file_antimage_v1_control_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevisionBump.ProtoReflect.Descriptor instead.
func (*RevisionBump) Descriptor() ([]byte, []int) {
	return file_antimage_v1_control_proto_rawDescGZIP(), []int{10}
}

func (x *RevisionBump) GetRevision() int64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

type FetchNow struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchNow) Reset() {
	*x = FetchNow{}
	mi := &file_antimage_v1_control_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchNow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchNow) ProtoMessage() {}

func (x *FetchNow) ProtoReflect() protoreflect.Message {
	mi := &file_antimage_v1_control_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchNow.ProtoReflect.Descriptor instead.
func (*FetchNow) Descriptor() ([]byte, []int) {
	return file_antimage_v1_control_proto_rawDescGZIP(), []int{11}
}

type UpgradeRequired struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	PanelProtocolVersion uint32                 `protobuf:"varint,1,opt,name=panel_protocol_version,json=panelProtocolVersion,proto3" json:"panel_protocol_version,omitempty"`
	DownloadUrl          string                 `protobuf:"bytes,2,opt,name=download_url,json=downloadUrl,proto3" json:"download_url,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *UpgradeRequired) Reset() {
	*x = UpgradeRequired{}
	mi := &file_antimage_v1_control_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpgradeRequired) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpgradeRequired) ProtoMessage() {}

func (x *UpgradeRequired) ProtoReflect() protoreflect.Message {
	mi := &file_antimage_v1_control_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpgradeRequired.ProtoReflect.Descriptor instead.
func (*UpgradeRequired) Descriptor() ([]byte, []int) {
	return file_antimage_v1_control_proto_rawDescGZIP(), []int{12}
}

func (x *UpgradeRequired) GetPanelProtocolVersion() uint32 {
	if x != nil {
		return x.PanelProtocolVersion
	}
	return 0
}

func (x *UpgradeRequired) GetDownloadUrl() string {
	if x != nil {
		return x.DownloadUrl
	}
	return ""
}

type SnapshotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        int64                  `protobuf:"varint,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnapshotRequest) Reset() {
	*x = SnapshotRequest{}
	mi := &file_antimage_v1_control_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotRequest) ProtoMessage() {}

func (x *SnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_antimage_v1_control_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotRequest.ProtoReflect.Descriptor instead.
func (*SnapshotRequest) Descriptor() ([]byte, []int) {
	return file_antimage_v1_control_proto_rawDescGZIP(), []int{13}
}

func (x *SnapshotRequest) GetNodeId() int64 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

type SnapshotResponse struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Revision int64                  `protobuf:"varint,1,opt,name=revision,proto3" json:"revision,omitempty"`
	// Exact canonical bytes. The agent re-hashes these before applying, so this
	// must stay `bytes` rather than a structured message that could re-encode.
	Document      []byte `protobuf:"bytes,2,opt,name=document,proto3" json:"document,omitempty"`
	Sha256        string `protobuf:"bytes,3,opt,name=sha256,proto3" json:"sha256,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnapshotResponse) Reset() {
	*x = SnapshotResponse{}
	mi := &file_antimage_v1_control_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotResponse) ProtoMessage() {}

func (x *SnapshotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_antimage_v1_control_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotResponse.ProtoReflect.Descriptor instead.
func (*SnapshotResponse) Descriptor() ([]byte, []int) {
	return file_antimage_v1_control_proto_rawDescGZIP(), []int{14}
}

func (x *SnapshotResponse) GetRevision() int64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

func (x *SnapshotResponse) GetDocument() []byte {
	if x != nil {
		return x.Document
	}
	return nil
}

func (x *SnapshotResponse) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

// UsageReport carries accounting deltas from one node. SP3 design decision 1:
// the agent computes deltas; the panel never reasons about raw counters.
type UsageReport struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	NodeId int64                  `protobuf:"varint,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	// Monotonic per node. Idempotency key: (node_id, sequence).
	Sequence      int64          `protobuf:"varint,2,opt,name=sequence,proto3" json:"sequence,omitempty"`
	Samples       []*UsageSample `protobuf:"bytes,3,rep,name=samples,proto3" json:"samples,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UsageReport) Reset() {
	*x = UsageReport{}
	mi := &file_antimage_v1_control_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UsageReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsageReport) ProtoMessage() {}

func (x *UsageReport) ProtoReflect() protoreflect.Message {
	mi := &file_antimage_v1_control_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsageReport.ProtoReflect.Descriptor instead.
func (*UsageReport) Descriptor() ([]byte, []int) {
	return file_antimage_v1_control_proto_rawDescGZIP(), []int{15}
}

func (x *UsageReport) GetNodeId() int64 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

func (x *UsageReport) GetSequence() int64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *UsageReport) GetSamples() []*UsageSample {
	if x != nil {
		return x.Samples
	}
	return nil
}

// UsageSample is one subject's traffic delta on one service since the last
// report.
type UsageSample struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SubjectId     int64                  `protobuf:"varint,1,opt,name=subject_id,json=subjectId,proto3" json:"subject_id,omitempty"`
	UplinkBytes   uint64                 `protobuf:"varint,2,opt,name=uplink_bytes,json=uplinkBytes,proto3" json:"uplink_bytes,omitempty"`
	DownlinkBytes uint64                 `protobuf:"varint,3,opt,name=downlink_bytes,json=downlinkBytes,proto3" json:"downlink_bytes,omitempty"`
	// Which service the traffic went through, when the adapter can attribute it
	// (C2). Zero means "not attributed", which the panel stores as NULL rather
	// than guessing: a node running one adapter that cannot attribute, or an
	// agent older than this field, both send zero and must keep accounting.
	//
	// Deliberately not optional. Proto3 scalar presence would distinguish "the
	// agent said zero" from "the agent said nothing", and there is nothing the
	// panel would do differently: both mean the same NULL.
	ServiceId     int64 `protobuf:"varint,4,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UsageSample) Reset() {
	*x = UsageSample{}
	mi := &file_antimage_v1_control_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UsageSample) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsageSample) ProtoMessage() {}

func (x *UsageSample) ProtoReflect() protoreflect.Message {
	mi := &file_antimage_v1_control_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsageSample.ProtoReflect.Descriptor instead.
func (*UsageSample) Descriptor() ([]byte, []int) {
	return file_antimage_v1_control_proto_rawDescGZIP(), []int{16}
}

func (x *UsageSample) GetSubjectId() int64 {
	if x != nil {
		return x.SubjectId
	}
	return 0
}

func (x *UsageSample) GetUplinkBytes() uint64 {
	if x != nil {
		return x.UplinkBytes
	}
	return 0
}

func (x *UsageSample) GetDownlinkBytes() uint64 {
	if x != nil {
		return x.DownlinkBytes
	}
	return 0
}

func (x *UsageSample) GetServiceId() int64 {
	if x != nil {
		return x.ServiceId
	}
	return 0
}

var File_antimage_v1_control_proto protoreflect.FileDescriptor

const file_antimage_v1_control_proto_rawDesc = "" +
	"\n" +
	"\x19antimage/v1/control.proto\x12\vantimage.v1\"\x8e\x01\n" +
	"\rEnrollRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x17\n" +
	"\acsr_der\x18\x02 \x01(\fR\x06csrDer\x12#\n" +
	"\ragent_version\x18\x03 \x01(\tR\fagentVersion\x12)\n" +
	"\x10protocol_version\x18\x04 \x01(\rR\x0fprotocolVersion\"[\n" +
	"\x0eEnrollResponse\x12\x19\n" +
	"\bcert_der\x18\x01 \x01(\fR\acertDer\x12\x15\n" +
	"\x06ca_der\x18\x02 \x01(\fR\x05caDer\x12\x17\n" +
	"\anode_id\x18\x03 \x01(\x03R\x06nodeId\"\xfb\x01\n" +
	"\fAgentMessage\x12*\n" +
	"\x05hello\x18\x01 \x01(\v2\x12.antimage.v1.HelloH\x00R\x05hello\x126\n" +
	"\theartbeat\x18\x02 \x01(\v2\x16.antimage.v1.HeartbeatH\x00R\theartbeat\x12=\n" +
	"\fapply_report\x18\x03 \x01(\v2\x18.antimage.v1.ApplyReportH\x00R\vapplyReport\x12=\n" +
	"\fusage_report\x18\x04 \x01(\v2\x18.antimage.v1.UsageReportH\x00R\vusageReportB\t\n" +
	"\apayload\"\xdc\x01\n" +
	"\fPanelMessage\x12@\n" +
	"\rrevision_bump\x18\x01 \x01(\v2\x19.antimage.v1.RevisionBumpH\x00R\frevisionBump\x124\n" +
	"\tfetch_now\x18\x02 \x01(\v2\x15.antimage.v1.FetchNowH\x00R\bfetchNow\x12I\n" +
	"\x10upgrade_required\x18\x03 \x01(\v2\x1c.antimage.v1.UpgradeRequiredH\x00R\x0fupgradeRequiredB\t\n" +
	"\apayload\"\xf6\x01\n" +
	"\x05Hello\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\x03R\x06nodeId\x12#\n" +
	"\ragent_version\x18\x02 \x01(\tR\fagentVersion\x12)\n" +
	"\x10protocol_version\x18\x03 \x01(\rR\x0fprotocolVersion\x12)\n" +
	"\x10applied_revision\x18\x04 \x01(\x03R\x0fappliedRevision\x12\x1d\n" +
	"\n" +
	"doc_sha256\x18\x05 \x01(\tR\tdocSha256\x12:\n" +
	"\badapters\x18\x06 \x03(\v2\x1e.antimage.v1.AdapterDescriptorR\badapters\"\xfa\x01\n" +
	"\x11AdapterDescriptor\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12 \n" +
	"\fhot_user_add\x18\x03 \x01(\bR\n" +
	"hotUserAdd\x12'\n" +
	"\x0fself_accounting\x18\x04 \x01(\bR\x0eselfAccounting\x12!\n" +
	"\frequires_pki\x18\x05 \x01(\bR\vrequiresPki\x12%\n" +
	"\x0eservice_schema\x18\x06 \x01(\fR\rserviceSchema\x12\"\n" +
	"\fcapabilities\x18\a \x03(\tR\fcapabilities\"\xb1\x01\n" +
	"\tHeartbeat\x12\x14\n" +
	"\x05load1\x18\x01 \x01(\x01R\x05load1\x12$\n" +
	"\x0emem_used_bytes\x18\x02 \x01(\x04R\fmemUsedBytes\x12%\n" +
	"\x0euptime_seconds\x18\x03 \x01(\x04R\ruptimeSeconds\x12A\n" +
	"\x0eadapter_health\x18\x04 \x03(\v2\x1a.antimage.v1.AdapterHealthR\radapterHealth\"K\n" +
	"\rAdapterHealth\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x0e\n" +
	"\x02ok\x18\x02 \x01(\bR\x02ok\x12\x16\n" +
	"\x06detail\x18\x03 \x01(\tR\x06detail\"\xd4\x01\n" +
	"\vApplyReport\x12'\n" +
	"\x0ftarget_revision\x18\x01 \x01(\x03R\x0etargetRevision\x12\x1c\n" +
	"\tconverged\x18\x02 \x01(\bR\tconverged\x12\x1a\n" +
	"\bdeferred\x18\x03 \x01(\bR\bdeferred\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\x12\x1d\n" +
	"\n" +
	"doc_sha256\x18\x05 \x01(\tR\tdocSha256\x12-\n" +
	"\x05steps\x18\x06 \x03(\v2\x17.antimage.v1.StepResultR\x05steps\"\x99\x01\n" +
	"\n" +
	"StepResult\x12\x10\n" +
	"\x03seq\x18\x01 \x01(\x05R\x03seq\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\x12\x1e\n" +
	"\n" +
	"disruption\x18\x03 \x01(\tR\n" +
	"disruption\x12\x0e\n" +
	"\x02ok\x18\x04 \x01(\bR\x02ok\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error\x12\x1f\n" +
	"\vduration_ms\x18\x06 \x01(\x03R\n" +
	"durationMs\"*\n" +
	"\fRevisionBump\x12\x1a\n" +
	"\brevision\x18\x01 \x01(\x03R\brevision\"\n" +
	"\n" +
	"\bFetchNow\"j\n" +
	"\x0fUpgradeRequired\x124\n" +
	"\x16panel_protocol_version\x18\x01 \x01(\rR\x14panelProtocolVersion\x12!\n" +
	"\fdownload_url\x18\x02 \x01(\tR\vdownloadUrl\"*\n" +
	"\x0fSnapshotRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\x03R\x06nodeId\"b\n" +
	"\x10SnapshotResponse\x12\x1a\n" +
	"\brevision\x18\x01 \x01(\x03R\brevision\x12\x1a\n" +
	"\bdocument\x18\x02 \x01(\fR\bdocument\x12\x16\n" +
	"\x06sha256\x18\x03 \x01(\tR\x06sha256\"v\n" +
	"\vUsageReport\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\x03R\x06nodeId\x12\x1a\n" +
	"\bsequence\x18\x02 \x01(\x03R\bsequence\x122\n" +
	"\asamples\x18\x03 \x03(\v2\x18.antimage.v1.UsageSampleR\asamples\"\x95\x01\n" +
	"\vUsageSample\x12\x1d\n" +
	"\n" +
	"subject_id\x18\x01 \x01(\x03R\tsubjectId\x12!\n" +
	"\fuplink_bytes\x18\x02 \x01(\x04R\vuplinkBytes\x12%\n" +
	"\x0edownlink_bytes\x18\x03 \x01(\x04R\rdownlinkBytes\x12\x1d\n" +
	"\n" +
	"service_id\x18\x04 \x01(\x03R\tserviceId2O\n" +
	"\n" +
	"Enrollment\x12A\n" +
	"\x06Enroll\x12\x1a.antimage.v1.EnrollRequest\x1a\x1b.antimage.v1.EnrollResponse2\xa0\x01\n" +
	"\aControl\x12B\n" +
	"\x06Stream\x12\x19.antimage.v1.AgentMessage\x1a\x19.antimage.v1.PanelMessage(\x010\x01\x12Q\n" +
	"\x12GetDesiredSnapshot\x12\x1c.antimage.v1.SnapshotRequest\x1a\x1d.antimage.v1.SnapshotResponseBHZFgithub.com/amyrm/antimage/internal/shared/proto/antimage/v1;antimagev1b\x06proto3"

var (
	file_antimage_v1_control_proto_rawDescOnce sync.Once
	file_antimage_v1_control_proto_rawDescData []byte
)

func file_antimage_v1_control_proto_rawDescGZIP() []byte {
	file_antimage_v1_control_proto_rawDescOnce.Do(func() {
		file_antimage_v1_control_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_antimage_v1_control_proto_rawDesc), len(file_antimage_v1_control_proto_rawDesc)))
	})
	return file_antimage_v1_control_proto_rawDescData
}

var file_antimage_v1_control_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_antimage_v1_control_proto_goTypes = []any{
	(*EnrollRequest)(nil),     // 0: antimage.v1.EnrollRequest
	(*EnrollResponse)(nil),    // 1: antimage.v1.EnrollResponse
	(*AgentMessage)(nil),      // 2: antimage.v1.AgentMessage
	(*PanelMessage)(nil),      // 3: antimage.v1.PanelMessage
	(*Hello)(nil),             // 4: antimage.v1.Hello
	(*AdapterDescriptor)(nil), // 5: antimage.v1.AdapterDescriptor
	(*Heartbeat)(nil),         // 6: antimage.v1.Heartbeat
	(*AdapterHealth)(nil),     // 7: antimage.v1.AdapterHealth
	(*ApplyReport)(nil),       // 8: antimage.v1.ApplyReport
	(*StepResult)(nil),        // 9: antimage.v1.StepResult
	(*RevisionBump)(nil),      // 10: antimage.v1.RevisionBump
	(*FetchNow)(nil),          // 11: antimage.v1.FetchNow
	(*UpgradeRequired)(nil),   // 12: antimage.v1.UpgradeRequired
	(*SnapshotRequest)(nil),   // 13: antimage.v1.SnapshotRequest
	(*SnapshotResponse)(nil),  // 14: antimage.v1.SnapshotResponse
	(*UsageReport)(nil),       // 15: antimage.v1.UsageReport
	(*UsageSample)(nil),       // 16: antimage.v1.UsageSample
}
var file_antimage_v1_control_proto_depIdxs = []int32{
	4,  // 0: antimage.v1.AgentMessage.hello:type_name -> antimage.v1.Hello
	6,  // 1: antimage.v1.AgentMessage.heartbeat:type_name -> antimage.v1.Heartbeat
	8,  // 2: antimage.v1.AgentMessage.apply_report:type_name -> antimage.v1.ApplyReport
	15, // 3: antimage.v1.AgentMessage.usage_report:type_name -> antimage.v1.UsageReport
	10, // 4: antimage.v1.PanelMessage.revision_bump:type_name -> antimage.v1.RevisionBump
	11, // 5: antimage.v1.PanelMessage.fetch_now:type_name -> antimage.v1.FetchNow
	12, // 6: antimage.v1.PanelMessage.upgrade_required:type_name -> antimage.v1.UpgradeRequired
	5,  // 7: antimage.v1.Hello.adapters:type_name -> antimage.v1.AdapterDescriptor
	7,  // 8: antimage.v1.Heartbeat.adapter_health:type_name -> antimage.v1.AdapterHealth
	9,  // 9: antimage.v1.ApplyReport.steps:type_name -> antimage.v1.StepResult
	16, // 10: antimage.v1.UsageReport.samples:type_name -> antimage.v1.UsageSample
	0,  // 11: antimage.v1.Enrollment.Enroll:input_type -> antimage.v1.EnrollRequest
	2,  // 12: antimage.v1.Control.Stream:input_type -> antimage.v1.AgentMessage
	13, // 13: antimage.v1.Control.GetDesiredSnapshot:input_type -> antimage.v1.SnapshotRequest
	1,  // 14: antimage.v1.Enrollment.Enroll:output_type -> antimage.v1.EnrollResponse
	3,  // 15: antimage.v1.Control.Stream:output_type -> antimage.v1.PanelMessage
	14, // 16: antimage.v1.Control.GetDesiredSnapshot:output_type -> antimage.v1.SnapshotResponse
	14, // [14:17] is the sub-list for method output_type
	11, // [11:14] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_antimage_v1_control_proto_init() }
func file_antimage_v1_control_proto_init() {
	if File_antimage_v1_control_proto != nil {
		return
	}
	file_antimage_v1_control_proto_msgTypes[2].OneofWrappers = []any{
		(*AgentMessage_Hello)(nil),
		(*AgentMessage_Heartbeat)(nil),
		(*AgentMessage_ApplyReport)(nil),
		(*AgentMessage_UsageReport)(nil),
	}
	file_antimage_v1_control_proto_msgTypes[3].OneofWrappers = []any{
		(*PanelMessage_RevisionBump)(nil),
		(*PanelMessage_FetchNow)(nil),
		(*PanelMessage_UpgradeRequired)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_antimage_v1_control_proto_rawDesc), len(file_antimage_v1_control_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_antimage_v1_control_proto_goTypes,
		DependencyIndexes: file_antimage_v1_control_proto_depIdxs,
		MessageInfos:      file_antimage_v1_control_proto_msgTypes,
	}.Build()
	File_antimage_v1_control_proto = out.File
	file_antimage_v1_control_proto_goTypes = nil
	file_antimage_v1_control_proto_depIdxs = nil
}
