// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: antimage/v1/control.proto

package antimagev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EnrollRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Single-use, 30 minute TTL, bound to one node.
	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	// The node's CSR. Its private key never leaves the host, and the panel
	// never sees it.
	CsrDer          []byte `protobuf:"bytes,2,opt,name=csr_der,json=csrDer,proto3" json:"csr_der,omitempty"`
	AgentVersion    string `protobuf:"bytes,3,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`
	ProtocolVersion uint32 `protobuf:"varint,4,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *EnrollRequest) Reset() {
	*x = EnrollRequest{}
	mi := &file_antimage_v1_control_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrollRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrollRequest) ProtoMessage() {}

func (x *EnrollRequest) ProtoReflect() protoreflect.Message {
	mi := &file_antimage_v1_control_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrollRequest.ProtoReflect.Descriptor instead.
func (*EnrollRequest) Descriptor() ([]byte, []int) {
	return file_antimage_v1_control_proto_rawDescGZIP(), []int{0}
}

func (x *EnrollRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *EnrollRequest) GetCsrDer() []byte {
	if x != nil {
		return x.CsrDer
	}
	return nil
}

func (x *EnrollRequest) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

func (x *EnrollRequest) GetProtocolVersion() uint32 {
	if x != nil {
		return x.ProtocolVersion
	}
	return 0
}

type EnrollResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Signed client certificate, CN = node id. The panel names the node; the
	// CSR's own subject is ignored so a node cannot name itself.
	CertDer []byte `protobuf:"bytes,1,opt,name=cert_der,json=certDer,proto3" json:"cert_der,omitempty"`
	// Panel CA, for verifying the panel on later connections.
	CaDer         []byte `protobuf:"bytes,2,opt,name=ca_der,json=caDer,proto3" json:"ca_der,omitempty"`
	NodeId        int64  `protobuf:"varint,3,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnrollResponse) Reset() {
	*x = EnrollResponse{}
	mi := &file_antimage_v1_control_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrollResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrollResponse) ProtoMessage() {}

func (x *EnrollResponse) ProtoReflect() protoreflect.Message {
	mi := &file_antimage_v1_control_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrollResponse.ProtoReflect.Descriptor instead.
func (*EnrollResponse) Descriptor() ([]byte, []int) {
	return file_antimage_v1_control_proto_rawDescGZIP(), []int{1}
}

func (x *EnrollResponse) GetCertDer() []byte {
	if x != nil {
		return x.CertDer
	}
	return nil
}

func (x *EnrollResponse) GetCaDer() []byte {
	if x != nil {
		return x.CaDer
	}
	return nil
}

func (x *EnrollResponse) GetNodeId() int64 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

type AgentMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*AgentMessage_Hello
	//	*AgentMessage_Heartbeat
	//	*AgentMessage_ApplyReport
	//	*AgentMessage_UsageReport
	//	*AgentMessage_CommandResult
	Payload       isAgentMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentMessage) Reset() {
	*x = AgentMessage{}
	mi := &file_antimage_v1_control_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentMessage) ProtoMessage() {}

func (x *AgentMessage) ProtoReflect() protoreflect.Message {
	mi := &file_antimage_v1_control_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentMessage.ProtoReflect.Descriptor instead.
func (*AgentMessage) Descriptor() ([]byte, []int) {
	return file_antimage_v1_control_proto_rawDescGZIP(), []int{2}
}

func (x *AgentMessage) GetPayload() isAgentMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *AgentMessage) GetHello() *Hello {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_Hello); ok {
			return x.Hello
		}
	}
	return nil
}

func (x *AgentMessage) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *AgentMessage) GetApplyReport() *ApplyReport {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_ApplyReport); ok {
			return x.ApplyReport
		}
	}
	return nil
}

func (x *AgentMessage) GetUsageReport() *UsageReport {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_UsageReport); ok {
			return x.UsageReport
		}
	}
	return nil
}

func (x *AgentMessage) GetCommandResult() *AgentCommandResult {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_CommandResult); ok {
			return x.CommandResult
		}
	}
	return nil
}

type isAgentMessage_Payload interface {
	isAgentMessage_Payload()
}

type AgentMessage_Hello struct {
	Hello *Hello `protobuf:"bytes,1,opt,name=hello,proto3,oneof"`
}

type AgentMessage_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,2,opt,name=heartbeat,proto3,oneof"`
}

type AgentMessage_ApplyReport struct {
	ApplyReport *ApplyReport `protobuf:"bytes,3,opt,name=apply_report,json=applyReport,proto3,oneof"`
}

type AgentMessage_UsageReport struct {
	UsageReport *UsageReport `protobuf:"bytes,4,opt,name=usage_report,json=usageReport,proto3,oneof"`
}

type AgentMessage_CommandResult struct {
	CommandResult *AgentCommandResult `protobuf:"bytes,5,opt,name=command_result,json=commandResult,proto3,oneof"`
}

func (*AgentMessage_Hello) isAgentMessage_Payload() {}

func (*AgentMessage_Heartbeat) isAgentMessage_Payload() {}

func (*AgentMessage_ApplyReport) isAgentMessage_Payload() {}

func (*AgentMessage_UsageReport) isAgentMessage_Payload() {}

func (*AgentMessage_CommandResult) isAgentMessage_Payload() {}

type PanelMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*PanelMessage_RevisionBump
	//	*PanelMessage_FetchNow
	//	*PanelMessage_UpgradeRequired
	//	*PanelMessage_Command
	Payload       isPanelMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PanelMessage) Reset() {
	*x = PanelMessage{}
	mi := &file_antimage_v1_control_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PanelMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PanelMessage) ProtoMessage() {}

func (x *PanelMessage) ProtoReflect() protoreflect.Message {
	mi := &file_antimage_v1_control_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PanelMessage.ProtoReflect.Descriptor instead.
func (*PanelMessage) Descriptor() ([]byte, []int) {
	return file_antimage_v1_control_proto_rawDescGZIP(), []int{3}
}

func (x *PanelMessage) GetPayload() isPanelMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *PanelMessage) GetRevisionBump() *RevisionBump {
	if x != nil {
		if x, ok := x.Payload.(*PanelMessage_RevisionBump); ok {
			return x.RevisionBump
		}
	}
	return nil
}

func (x *PanelMessage) GetFetchNow() *FetchNow {
	if x != nil {
		if x, ok := x.Payload.(*PanelMessage_FetchNow); ok {
			return x.FetchNow
		}
	}
	return nil
}

func (x *PanelMessage) GetUpgradeRequired() *UpgradeRequired {
	if x != nil {
		if x, ok := x.Payload.(*PanelMessage_UpgradeRequired); ok {
			return x.UpgradeRequired
		}
	}
	return nil
}

func (x *PanelMessage) GetCommand() *AgentCommand {
	if x != nil {
		if x, ok := x.Payload.(*PanelMessage_Command); ok {
			return x.Command
		}
	}
	return nil
}

type isPanelMessage_Payload interface {
	isPanelMessage_Payload()
}

type PanelMessage_RevisionBump struct {
	RevisionBump *RevisionBump `protobuf:"bytes,1,opt,name=revision_bump,json=revisionBump,proto3,oneof"`
}

type PanelMessage_FetchNow struct {
	FetchNow *FetchNow `protobuf:"bytes,2,opt,name=fetch_now,json=fetchNow,proto3,oneof"`
}

type PanelMessage_UpgradeRequired struct {
	UpgradeRequired *UpgradeRequired `protobuf:"bytes,3,opt,name=upgrade_required,json=upgradeRequired,proto3,oneof"`
}

type PanelMessage_Command struct {
	Command *AgentCommand `protobuf:"bytes,4,opt,name=command,proto3,oneof"`
}

func (*PanelMessage_RevisionBump) isPanelMessage_Payload() {}

func (*PanelMessage_FetchNow) isPanelMessage_Payload() {}

func (*PanelMessage_UpgradeRequired) isPanelMessage_Payload() {}

func (*PanelMessage_Command) isPanelMessage_Payload() {}

// AgentCommand is the panel asking the agent to do something ON DEMAND,
// outside the desired-state reconciliation loop -- restarting a service the
// operator clicked, pulling a fresh geo database, installing a precise core
// version, or fetching a log tail. It exists separately from
// RevisionBump/FetchNow because those two both mean
// "converge toward the desired document", and an on-demand action is not a
// convergence request: a restart with no config change has nothing to
// converge, and this command is what asks for it anyway.
//
// command_id correlates this to its AgentCommandResult. It is a string
// rather than reusing the desired_revision or any DB primary key, because a
// command is not a row anywhere -- the panel's Hub only needs to remember it
// long enough to wake whichever HTTP request is waiting, and does not
// persist it. A UUID generated per HTTP request satisfies that with no
// coordination against any other id space.
type AgentCommand struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	CommandId string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	// Types that are valid to be assigned to Body:
	//
	//	*AgentCommand_RestartAdapters
	//	*AgentCommand_UpdateGeoData
	//	*AgentCommand_UpgradeCore
	//	*AgentCommand_FetchLogs
	Body          isAgentCommand_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentCommand) Reset() {
	*x = AgentCommand{}
	mi := &file_antimage_v1_control_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentCommand) ProtoMessage() {}

func (x *AgentCommand) ProtoReflect() protoreflect.Message {
	mi := &file_antimage_v1_control_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentCommand.ProtoReflect.Descriptor instead.
func (*AgentCommand) Descriptor() ([]byte, []int) {
	return file_antimage_v1_control_proto_rawDescGZIP(), []int{4}
}

func (x *AgentCommand) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *AgentCommand) GetBody() isAgentCommand_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *AgentCommand) GetRestartAdapters() *RestartAdapters {
	if x != nil {
		if x, ok := x.Body.(*AgentCommand_RestartAdapters); ok {
			return x.RestartAdapters
		}
	}
	return nil
}

func (x *AgentCommand) GetUpdateGeoData() *UpdateGeoData {
	if x != nil {
		if x, ok := x.Body.(*AgentCommand_UpdateGeoData); ok {
			return x.UpdateGeoData
		}
	}
	return nil
}

func (x *AgentCommand) GetUpgradeCore() *UpgradeCore {
	if x != nil {
		if x, ok := x.Body.(*AgentCommand_UpgradeCore); ok {
			return x.UpgradeCore
		}
	}
	return nil
}

func (x *AgentCommand) GetFetchLogs() *FetchLogs {
	if x != nil {
		if x, ok := x.Body.(*AgentCommand_FetchLogs); ok {
			return x.FetchLogs
		}
	}
	return nil
}

type isAgentCommand_Body interface {
	isAgentCommand_Body()
}

type AgentCommand_RestartAdapters struct {
	RestartAdapters *RestartAdapters `protobuf:"bytes,2,opt,name=restart_adapters,json=restartAdapters,proto3,oneof"`
}

type AgentCommand_UpdateGeoData struct {
	UpdateGeoData *UpdateGeoData `protobuf:"bytes,3,opt,name=update_geo_data,json=updateGeoData,proto3,oneof"`
}

type AgentCommand_UpgradeCore struct {
	UpgradeCore *UpgradeCore `protobuf:"bytes,4,opt,name=upgrade_core,json=upgradeCore,proto3,oneof"`
}

type AgentCommand_FetchLogs struct {
	FetchLogs *FetchLogs `protobuf:"bytes,5,opt,name=fetch_logs,json=fetchLogs,proto3,oneof"`
}

func (*AgentCommand_RestartAdapters) isAgentCommand_Body() {}

func (*AgentCommand_UpdateGeoData) isAgentCommand_Body() {}

func (*AgentCommand_UpgradeCore) isAgentCommand_Body() {}

func (*AgentCommand_FetchLogs) isAgentCommand_Body() {}

// RestartAdapters names which adapter kinds to restart. Empty means every
// adapter this node currently runs -- explicit rather than a sentinel value,
// so a caller who really does mean "just xray" is not one typo away from
// restarting everything.
type RestartAdapters struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kinds         []string               `protobuf:"bytes,1,rep,name=kinds,proto3" json:"kinds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestartAdapters) Reset() {
	*x = RestartAdapters{}
	mi := &file_antimage_v1_control_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestartAdapters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestartAdapters) ProtoMessage() {}

func (x *RestartAdapters) ProtoReflect() protoreflect.Message {
	mi := &file_antimage_v1_control_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestartAdapters.ProtoReflect.Descriptor instead.
func (*RestartAdapters) Descriptor() ([]byte, []int) {
	return file_antimage_v1_control_proto_rawDescGZIP(), []int{5}
}

func (x *RestartAdapters) GetKinds() []string {
	if x != nil {
		return x.Kinds
	}
	return nil
}

// UpdateGeoData asks the agent to fetch fresh geoip/geosite databases and
// restart whichever adapter uses them. The panel supplies the URLs rather
// than the agent hardcoding an upstream: an operator behind a mirror or
// firewall can point at their own copy without an agent upgrade, and there
// is exactly one place -- the panel -- that decides which source a fleet
// trusts.
//
// Xray reads geo data once at process start, not on SIGHUP/reload, so
// "update" without a restart would download a file nothing reads; the
// agent restarts the adapter itself once the new files verify, using the
// same Adapter.Restart path RestartAdapters uses.
type UpdateGeoData struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	GeoipUrl         string                 `protobuf:"bytes,1,opt,name=geoip_url,json=geoipUrl,proto3" json:"geoip_url,omitempty"`
	GeoipSha256Url   string                 `protobuf:"bytes,2,opt,name=geoip_sha256_url,json=geoipSha256Url,proto3" json:"geoip_sha256_url,omitempty"`
	GeositeUrl       string                 `protobuf:"bytes,3,opt,name=geosite_url,json=geositeUrl,proto3" json:"geosite_url,omitempty"`
	GeositeSha256Url string                 `protobuf:"bytes,4,opt,name=geosite_sha256_url,json=geositeSha256Url,proto3" json:"geosite_sha256_url,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *UpdateGeoData) Reset() {
	*x = UpdateGeoData{}
	mi := &file_antimage_v1_control_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateGeoData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateGeoData) ProtoMessage() {}

func (x *UpdateGeoData) ProtoReflect() protoreflect.Message {
	mi := &file_antimage_v1_control_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateGeoData.ProtoReflect.Descriptor instead.
func (*UpdateGeoData) Descriptor() ([]byte, []int) {
	return file_antimage_v1_control_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateGeoData) GetGeoipUrl() string {
	if x != nil {
		return x.GeoipUrl
	}
	return ""
}

func (x *UpdateGeoData) GetGeoipSha256Url() string {
	if x != nil {
		return x.GeoipSha256Url
	}
	return ""
}

func (x *UpdateGeoData) GetGeositeUrl() string {
	if x != nil {
		return x.GeositeUrl
	}
	return ""
}

func (x *UpdateGeoData) GetGeositeSha256Url() string {
	if x != nil {
		return x.GeositeSha256Url
	}
	return ""
}

// UpgradeCore asks the agent to install a SPECIFIC core binary, unlike
// UpdateGeoData there is deliberately no "default source" anywhere in this
// path: a data file that turns out wrong degrades routing accuracy, but an
// executable that turns out wrong can take a node fully offline, and that
// is not a choice this system makes on an operator's behalf. kind and
// binary_sha256 are both required for the same reason -- kind picks which
// adapter (a node can run xray and sing-box together, with unrelated
// version cadences), and the checksum is not fetched from a companion URL
// the way geo data's is: the panel resolves it once, from whatever
// manifest format that release actually publishes, so the agent's own
// verification logic never has to parse a new checksum format because an
// upstream changed how it publishes one.
type UpgradeCore struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Kind         string                 `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	BinaryUrl    string                 `protobuf:"bytes,2,opt,name=binary_url,json=binaryUrl,proto3" json:"binary_url,omitempty"`
	BinarySha256 string                 `protobuf:"bytes,3,opt,name=binary_sha256,json=binarySha256,proto3" json:"binary_sha256,omitempty"`
	// expected_version is checked against `<binary> -version` output during
	// the preflight, BEFORE the running installation is touched at all. Not
	// exact-match -- Xray's own -version output carries a date and build
	// tags around the number -- just Contains(), which is enough to catch
	// "the URL served the wrong release" without the agent needing to parse
	// a version string format that could change out from under it.
	ExpectedVersion string `protobuf:"bytes,4,opt,name=expected_version,json=expectedVersion,proto3" json:"expected_version,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UpgradeCore) Reset() {
	*x = UpgradeCore{}
	mi := &file_antimage_v1_control_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpgradeCore) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpgradeCore) ProtoMessage() {}

func (x *UpgradeCore) ProtoReflect() protoreflect.Message {
	mi := &file_antimage_v1_control_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpgradeCore.ProtoReflect.Descriptor instead.
func (*UpgradeCore) Descriptor() ([]byte, []int) {
	return file_antimage_v1_control_proto_rawDescGZIP(), []int{7}
}

func (x *UpgradeCore) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *UpgradeCore) GetBinaryUrl() string {
	if x != nil {
		return x.BinaryUrl
	}
	return ""
}

func (x *UpgradeCore) GetBinarySha256() string {
	if x != nil {
		return x.BinarySha256
	}
	return ""
}

func (x *UpgradeCore) GetExpectedVersion() string {
	if x != nil {
		return x.ExpectedVersion
	}
	return ""
}

type AgentCommandResult struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	CommandId string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	// Types that are valid to be assigned to Body:
	//
	//	*AgentCommandResult_RestartAdapters
	//	*AgentCommandResult_UpdateGeoData
	//	*AgentCommandResult_UpgradeCore
	//	*AgentCommandResult_FetchLogs
	Body          isAgentCommandResult_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentCommandResult) Reset() {
	*x = AgentCommandResult{}
	mi := &file_antimage_v1_control_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentCommandResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentCommandResult) ProtoMessage() {}

func (x *AgentCommandResult) ProtoReflect() protoreflect.Message {
	mi := &file_antimage_v1_control_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentCommandResult.ProtoReflect.Descriptor instead.
func (*AgentCommandResult) Descriptor() ([]byte, []int) {
	return file_antimage_v1_control_proto_rawDescGZIP(), []int{8}
}

func (x *AgentCommandResult) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *AgentCommandResult) GetBody() isAgentCommandResult_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *AgentCommandResult) GetRestartAdapters() *RestartAdaptersResult {
	if x != nil {
		if x, ok := x.Body.(*AgentCommandResult_RestartAdapters); ok {
			return x.RestartAdapters
		}
	}
	return nil
}

func (x *AgentCommandResult) GetUpdateGeoData() *UpdateGeoDataResult {
	if x != nil {
		if x, ok := x.Body.(*AgentCommandResult_UpdateGeoData); ok {
			return x.UpdateGeoData
		}
	}
	return nil
}

func (x *AgentCommandResult) GetUpgradeCore() *UpgradeCoreResult {
	if x != nil {
		if x, ok := x.Body.(*AgentCommandResult_UpgradeCore); ok {
			return x.UpgradeCore
		}
	}
	return nil
}

func (x *AgentCommandResult) GetFetchLogs() *FetchLogsResult {
	if x != nil {
		if x, ok := x.Body.(*AgentCommandResult_FetchLogs); ok {
			return x.FetchLogs
		}
	}
	return nil
}

type isAgentCommandResult_Body interface {
	isAgentCommandResult_Body()
}

type AgentCommandResult_RestartAdapters struct {
	RestartAdapters *RestartAdaptersResult `protobuf:"bytes,2,opt,name=restart_adapters,json=restartAdapters,proto3,oneof"`
}

type AgentCommandResult_UpdateGeoData struct {
	UpdateGeoData *UpdateGeoDataResult `protobuf:"bytes,3,opt,name=update_geo_data,json=updateGeoData,proto3,oneof"`
}

type AgentCommandResult_UpgradeCore struct {
	UpgradeCore *UpgradeCoreResult `protobuf:"bytes,4,opt,name=upgrade_core,json=upgradeCore,proto3,oneof"`
}

type AgentCommandResult_FetchLogs struct {
	FetchLogs *FetchLogsResult `protobuf:"bytes,5,opt,name=fetch_logs,json=fetchLogs,proto3,oneof"`
}

func (*AgentCommandResult_RestartAdapters) isAgentCommandResult_Body() {}

func (*AgentCommandResult_UpdateGeoData) isAgentCommandResult_Body() {}

func (*AgentCommandResult_UpgradeCore) isAgentCommandResult_Body() {}

func (*AgentCommandResult_FetchLogs) isAgentCommandResult_Body() {}

// FetchLogs asks the agent for the tail of ONE named adapter's own recent
// runtime log output. Targets exactly one kind, the same reasoning as
// UpgradeCore: a node running xray and sing-box together has two unrelated
// log streams, and "fetch logs" with no kind specified would not have a
// single correct meaning.
type FetchLogs struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Kind  string                 `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	// lines is how many trailing lines to return. The agent clamps this to
	// its own sane maximum rather than trusting the panel not to ask for
	// everything the log source has ever recorded.
	Lines         int32 `protobuf:"varint,2,opt,name=lines,proto3" json:"lines,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchLogs) Reset() {
	*x = FetchLogs{}
	mi := &file_antimage_v1_control_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchLogs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchLogs) ProtoMessage() {}

func (x *FetchLogs) ProtoReflect() protoreflect.Message {
	mi := &file_antimage_v1_control_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchLogs.ProtoReflect.Descriptor instead.
func (*FetchLogs) Descriptor() ([]byte, []int) {
	return file_antimage_v1_control_proto_rawDescGZIP(), []int{9}
}

func (x *FetchLogs) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *FetchLogs) GetLines() int32 {
	if x != nil {
		return x.Lines
	}
	return 0
}

// FetchLogsResult carries one adapter's raw recent log text, newest last
// (the convention `tail`/`journalctl` already follow), or an error
// explaining why there is none. Unlike UpgradeCoreResult there is no
// separate Found/Capable distinction on the wire -- see
// Registry.ReadLogs, which folds both into one error string here because,
// unlike a core upgrade, nothing was attempted that could partially
// succeed: either a readable adapter of this kind exists, or it does not.
type FetchLogsResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Kind  string                 `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	Ok    bool                   `protobuf:"varint,2,opt,name=ok,proto3" json:"ok,omitempty"`
	Logs  string                 `protobuf:"bytes,3,opt,name=logs,proto3" json:"logs,omitempty"`
	// Empty when ok.
	Error         string `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchLogsResult) Reset() {
	*x = FetchLogsResult{}
	mi := &file_antimage_v1_control_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchLogsResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchLogsResult) ProtoMessage() {}

func (x *FetchLogsResult) ProtoReflect() protoreflect.Message {
	mi := &file_antimage_v1_control_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchLogsResult.ProtoReflect.Descriptor instead.
func (*FetchLogsResult) Descriptor() ([]byte, []int) {
	return file_antimage_v1_control_proto_rawDescGZIP(), []int{10}
}

func (x *FetchLogsResult) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *FetchLogsResult) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *FetchLogsResult) GetLogs() string {
	if x != nil {
		return x.Logs
	}
	return ""
}

func (x *FetchLogsResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// UpgradeCoreResult reports what is actually installed and running RIGHT
// NOW, not just whether the download succeeded. RolledBack=true with
// Ok=false means the new binary was installed, failed to come up healthy,
// and the agent already reverted to the previous one and restarted it --
// the node is not sitting broken waiting for a human, but the upgrade did
// not take, and both facts have to reach the operator in one message.
type UpgradeCoreResult struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Kind             string                 `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	Ok               bool                   `protobuf:"varint,2,opt,name=ok,proto3" json:"ok,omitempty"`
	InstalledVersion string                 `protobuf:"bytes,3,opt,name=installed_version,json=installedVersion,proto3" json:"installed_version,omitempty"`
	RolledBack       bool                   `protobuf:"varint,4,opt,name=rolled_back,json=rolledBack,proto3" json:"rolled_back,omitempty"`
	// Empty when ok.
	Error         string `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpgradeCoreResult) Reset() {
	*x = UpgradeCoreResult{}
	mi := &file_antimage_v1_control_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpgradeCoreResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpgradeCoreResult) ProtoMessage() {}

func (x *UpgradeCoreResult) ProtoReflect() protoreflect.Message {
	mi := &file_antimage_v1_control_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpgradeCoreResult.ProtoReflect.Descriptor instead.
func (*UpgradeCoreResult) Descriptor() ([]byte, []int) {
	return file_antimage_v1_control_proto_rawDescGZIP(), []int{11}
}

func (x *UpgradeCoreResult) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *UpgradeCoreResult) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *UpgradeCoreResult) GetInstalledVersion() string {
	if x != nil {
		return x.InstalledVersion
	}
	return ""
}

func (x *UpgradeCoreResult) GetRolledBack() bool {
	if x != nil {
		return x.RolledBack
	}
	return false
}

func (x *UpgradeCoreResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type UpdateGeoDataResult struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Outcomes      []*AdapterGeoUpdateOutcome `protobuf:"bytes,1,rep,name=outcomes,proto3" json:"outcomes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateGeoDataResult) Reset() {
	*x = UpdateGeoDataResult{}
	mi := &file_antimage_v1_control_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateGeoDataResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateGeoDataResult) ProtoMessage() {}

func (x *UpdateGeoDataResult) ProtoReflect() protoreflect.Message {
	mi := &file_antimage_v1_control_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateGeoDataResult.ProtoReflect.Descriptor instead.
func (*UpdateGeoDataResult) Descriptor() ([]byte, []int) {
	return file_antimage_v1_control_proto_rawDescGZIP(), []int{12}
}

func (x *UpdateGeoDataResult) GetOutcomes() []*AdapterGeoUpdateOutcome {
	if x != nil {
		return x.Outcomes
	}
	return nil
}

// AdapterGeoUpdateOutcome is per adapter kind, so a node running xray
// alongside wireguard reports xray's real outcome without wireguard's
// unrelated presence changing anything about it.
//
// Unlike AdapterRestartOutcome, adapters with no geo-database concept at
// all do NOT get a row here -- most of the protocols this codebase drives
// have no domain/IP category routing, and listing five "unsupported" rows
// for a node that only runs xray would be noise, not signal. An empty
// outcomes list means no adapter on this node has geo data to update at
// all, which the caller reports as its own clear condition rather than as
// a silent no-op success.
type AdapterGeoUpdateOutcome struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          string                 `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	Ok            bool                   `protobuf:"varint,2,opt,name=ok,proto3" json:"ok,omitempty"`
	GeoipSha256   string                 `protobuf:"bytes,3,opt,name=geoip_sha256,json=geoipSha256,proto3" json:"geoip_sha256,omitempty"`
	GeositeSha256 string                 `protobuf:"bytes,4,opt,name=geosite_sha256,json=geositeSha256,proto3" json:"geosite_sha256,omitempty"`
	// Empty when ok.
	Error         string `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdapterGeoUpdateOutcome) Reset() {
	*x = AdapterGeoUpdateOutcome{}
	mi := &file_antimage_v1_control_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdapterGeoUpdateOutcome) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdapterGeoUpdateOutcome) ProtoMessage() {}

func (x *AdapterGeoUpdateOutcome) ProtoReflect() protoreflect.Message {
	mi := &file_antimage_v1_control_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdapterGeoUpdateOutcome.ProtoReflect.Descriptor instead.
func (*AdapterGeoUpdateOutcome) Descriptor() ([]byte, []int) {
	return file_antimage_v1_control_proto_rawDescGZIP(), []int{13}
}

func (x *AdapterGeoUpdateOutcome) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *AdapterGeoUpdateOutcome) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *AdapterGeoUpdateOutcome) GetGeoipSha256() string {
	if x != nil {
		return x.GeoipSha256
	}
	return ""
}

func (x *AdapterGeoUpdateOutcome) GetGeositeSha256() string {
	if x != nil {
		return x.GeositeSha256
	}
	return ""
}

func (x *AdapterGeoUpdateOutcome) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type RestartAdaptersResult struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Outcomes      []*AdapterRestartOutcome `protobuf:"bytes,1,rep,name=outcomes,proto3" json:"outcomes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestartAdaptersResult) Reset() {
	*x = RestartAdaptersResult{}
	mi := &file_antimage_v1_control_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestartAdaptersResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestartAdaptersResult) ProtoMessage() {}

func (x *RestartAdaptersResult) ProtoReflect() protoreflect.Message {
	mi := &file_antimage_v1_control_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestartAdaptersResult.ProtoReflect.Descriptor instead.
func (*RestartAdaptersResult) Descriptor() ([]byte, []int) {
	return file_antimage_v1_control_proto_rawDescGZIP(), []int{14}
}

func (x *RestartAdaptersResult) GetOutcomes() []*AdapterRestartOutcome {
	if x != nil {
		return x.Outcomes
	}
	return nil
}

// AdapterRestartOutcome is per adapter kind, because a node running xray and
// wireguard together can have one restart and the other refuse -- wireguard
// has no restartable daemon in the systemd sense, and reporting that
// truthfully as unsupported is the whole point of doing this per-kind rather
// than collapsing to one ok/error for the node.
type AdapterRestartOutcome struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Kind  string                 `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	Ok    bool                   `protobuf:"varint,2,opt,name=ok,proto3" json:"ok,omitempty"`
	// Empty when ok. "unsupported: <reason>" when the adapter kind has no
	// restart concept, never silently ok.
	Error         string `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdapterRestartOutcome) Reset() {
	*x = AdapterRestartOutcome{}
	mi := &file_antimage_v1_control_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdapterRestartOutcome) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdapterRestartOutcome) ProtoMessage() {}

func (x *AdapterRestartOutcome) ProtoReflect() protoreflect.Message {
	mi := &file_antimage_v1_control_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdapterRestartOutcome.ProtoReflect.Descriptor instead.
func (*AdapterRestartOutcome) Descriptor() ([]byte, []int) {
	return file_antimage_v1_control_proto_rawDescGZIP(), []int{15}
}

func (x *AdapterRestartOutcome) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *AdapterRestartOutcome) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *AdapterRestartOutcome) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type Hello struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	NodeId          int64                  `protobuf:"varint,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	AgentVersion    string                 `protobuf:"bytes,2,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`
	ProtocolVersion uint32                 `protobuf:"varint,3,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	AppliedRevision int64                  `protobuf:"varint,4,opt,name=applied_revision,json=appliedRevision,proto3" json:"applied_revision,omitempty"`
	DocSha256       string                 `protobuf:"bytes,5,opt,name=doc_sha256,json=docSha256,proto3" json:"doc_sha256,omitempty"`
	Adapters        []*AdapterDescriptor   `protobuf:"bytes,6,rep,name=adapters,proto3" json:"adapters,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Hello) Reset() {
	*x = Hello{}
	mi := &file_antimage_v1_control_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hello) ProtoMessage() {}

func (x *Hello) ProtoReflect() protoreflect.Message {
	mi := &file_antimage_v1_control_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hello.ProtoReflect.Descriptor instead.
func (*Hello) Descriptor() ([]byte, []int) {
	return file_antimage_v1_control_proto_rawDescGZIP(), []int{16}
}

func (x *Hello) GetNodeId() int64 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

func (x *Hello) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

func (x *Hello) GetProtocolVersion() uint32 {
	if x != nil {
		return x.ProtocolVersion
	}
	return 0
}

func (x *Hello) GetAppliedRevision() int64 {
	if x != nil {
		return x.AppliedRevision
	}
	return 0
}

func (x *Hello) GetDocSha256() string {
	if x != nil {
		return x.DocSha256
	}
	return ""
}

func (x *Hello) GetAdapters() []*AdapterDescriptor {
	if x != nil {
		return x.Adapters
	}
	return nil
}

type AdapterDescriptor struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Kind           string                 `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	Version        string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	HotUserAdd     bool                   `protobuf:"varint,3,opt,name=hot_user_add,json=hotUserAdd,proto3" json:"hot_user_add,omitempty"`
	SelfAccounting bool                   `protobuf:"varint,4,opt,name=self_accounting,json=selfAccounting,proto3" json:"self_accounting,omitempty"`
	RequiresPki    bool                   `protobuf:"varint,5,opt,name=requires_pki,json=requiresPki,proto3" json:"requires_pki,omitempty"`
	// JSON Schema for this adapter's service params. The panel validates
	// writes against it and the UI renders forms from it.
	ServiceSchema []byte   `protobuf:"bytes,6,opt,name=service_schema,json=serviceSchema,proto3" json:"service_schema,omitempty"`
	Capabilities  []string `protobuf:"bytes,7,rep,name=capabilities,proto3" json:"capabilities,omitempty"` // SP5: adapter capabilities (e.g., ["tls", "ws", "grpc"])
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdapterDescriptor) Reset() {
	*x = AdapterDescriptor{}
	mi := &file_antimage_v1_control_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdapterDescriptor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdapterDescriptor) ProtoMessage() {}

func (x *AdapterDescriptor) ProtoReflect() protoreflect.Message {
	mi := &file_antimage_v1_control_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdapterDescriptor.ProtoReflect.Descriptor instead.
func (*AdapterDescriptor) Descriptor() ([]byte, []int) {
	return file_antimage_v1_control_proto_rawDescGZIP(), []int{17}
}

func (x *AdapterDescriptor) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *AdapterDescriptor) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *AdapterDescriptor) GetHotUserAdd() bool {
	if x != nil {
		return x.HotUserAdd
	}
	return false
}

func (x *AdapterDescriptor) GetSelfAccounting() bool {
	if x != nil {
		return x.SelfAccounting
	}
	return false
}

func (x *AdapterDescriptor) GetRequiresPki() bool {
	if x != nil {
		return x.RequiresPki
	}
	return false
}

func (x *AdapterDescriptor) GetServiceSchema() []byte {
	if x != nil {
		return x.ServiceSchema
	}
	return nil
}

func (x *AdapterDescriptor) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

type Heartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Load1         float64                `protobuf:"fixed64,1,opt,name=load1,proto3" json:"load1,omitempty"`
	MemUsedBytes  uint64                 `protobuf:"varint,2,opt,name=mem_used_bytes,json=memUsedBytes,proto3" json:"mem_used_bytes,omitempty"`
	UptimeSeconds uint64                 `protobuf:"varint,3,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	AdapterHealth []*AdapterHealth       `protobuf:"bytes,4,rep,name=adapter_health,json=adapterHealth,proto3" json:"adapter_health,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_antimage_v1_control_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_antimage_v1_control_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_antimage_v1_control_proto_rawDescGZIP(), []int{18}
}

func (x *Heartbeat) GetLoad1() float64 {
	if x != nil {
		return x.Load1
	}
	return 0
}

func (x *Heartbeat) GetMemUsedBytes() uint64 {
	if x != nil {
		return x.MemUsedBytes
	}
	return 0
}

func (x *Heartbeat) GetUptimeSeconds() uint64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

func (x *Heartbeat) GetAdapterHealth() []*AdapterHealth {
	if x != nil {
		return x.AdapterHealth
	}
	return nil
}

type AdapterHealth struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          string                 `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	Ok            bool                   `protobuf:"varint,2,opt,name=ok,proto3" json:"ok,omitempty"`
	Detail        string                 `protobuf:"bytes,3,opt,name=detail,proto3" json:"detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdapterHealth) Reset() {
	*x = AdapterHealth{}
	mi := &file_antimage_v1_control_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdapterHealth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdapterHealth) ProtoMessage() {}

func (x *AdapterHealth) ProtoReflect() protoreflect.Message {
	mi := &file_antimage_v1_control_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdapterHealth.ProtoReflect.Descriptor instead.
func (*AdapterHealth) Descriptor() ([]byte, []int) {
	return file_antimage_v1_control_proto_rawDescGZIP(), []int{19}
}

func (x *AdapterHealth) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *AdapterHealth) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *AdapterHealth) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

type ApplyReport struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TargetRevision int64                  `protobuf:"varint,1,opt,name=target_revision,json=targetRevision,proto3" json:"target_revision,omitempty"`
	Converged      bool                   `protobuf:"varint,2,opt,name=converged,proto3" json:"converged,omitempty"`
	Deferred       bool                   `protobuf:"varint,3,opt,name=deferred,proto3" json:"deferred,omitempty"`
	Error          string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	// The hash the agent actually applied. The panel compares this against the
	// hash it recorded for target_revision; a match on revision with a mismatch
	// here is an integrity fault, never convergence.
	DocSha256     string        `protobuf:"bytes,5,opt,name=doc_sha256,json=docSha256,proto3" json:"doc_sha256,omitempty"`
	Steps         []*StepResult `protobuf:"bytes,6,rep,name=steps,proto3" json:"steps,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyReport) Reset() {
	*x = ApplyReport{}
	mi := &file_antimage_v1_control_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyReport) ProtoMessage() {}

func (x *ApplyReport) ProtoReflect() protoreflect.Message {
	mi := &file_antimage_v1_control_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyReport.ProtoReflect.Descriptor instead.
func (*ApplyReport) Descriptor() ([]byte, []int) {
	return file_antimage_v1_control_proto_rawDescGZIP(), []int{20}
}

func (x *ApplyReport) GetTargetRevision() int64 {
	if x != nil {
		return x.TargetRevision
	}
	return 0
}

func (x *ApplyReport) GetConverged() bool {
	if x != nil {
		return x.Converged
	}
	return false
}

func (x *ApplyReport) GetDeferred() bool {
	if x != nil {
		return x.Deferred
	}
	return false
}

func (x *ApplyReport) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ApplyReport) GetDocSha256() string {
	if x != nil {
		return x.DocSha256
	}
	return ""
}

func (x *ApplyReport) GetSteps() []*StepResult {
	if x != nil {
		return x.Steps
	}
	return nil
}

type StepResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Seq   int32                  `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"`
	Kind  string                 `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	// "none" | "reload" | "restart"
	Disruption    string `protobuf:"bytes,3,opt,name=disruption,proto3" json:"disruption,omitempty"`
	Ok            bool   `protobuf:"varint,4,opt,name=ok,proto3" json:"ok,omitempty"`
	Error         string `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	DurationMs    int64  `protobuf:"varint,6,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StepResult) Reset() {
	*x = StepResult{}
	mi := &file_antimage_v1_control_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StepResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StepResult) ProtoMessage() {}

func (x *StepResult) ProtoReflect() protoreflect.Message {
	mi := &file_antimage_v1_control_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StepResult.ProtoReflect.Descriptor instead.
func (*StepResult) Descriptor() ([]byte, []int) {
	return file_antimage_v1_control_proto_rawDescGZIP(), []int{21}
}

func (x *StepResult) GetSeq() int32 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *StepResult) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *StepResult) GetDisruption() string {
	if x != nil {
		return x.Disruption
	}
	return ""
}

func (x *StepResult) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *StepResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *StepResult) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

type RevisionBump struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Revision      int64                  `protobuf:"varint,1,opt,name=revision,proto3" json:"revision,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevisionBump) Reset() {
	*x = RevisionBump{}
	mi := &file_antimage_v1_control_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevisionBump) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevisionBump) ProtoMessage() {}

func (x *RevisionBump) ProtoReflect() protoreflect.Message {
	mi := &file_antimage_v1_control_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevisionBump.ProtoReflect.Descriptor instead.
func (*RevisionBump) Descriptor() ([]byte, []int) {
	return file_antimage_v1_control_proto_rawDescGZIP(), []int{22}
}

func (x *RevisionBump) GetRevision() int64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

type FetchNow struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchNow) Reset() {
	*x = FetchNow{}
	mi := &file_antimage_v1_control_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchNow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchNow) ProtoMessage() {}

func (x *FetchNow) ProtoReflect() protoreflect.Message {
	mi := &file_antimage_v1_control_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchNow.ProtoReflect.Descriptor instead.
func (*FetchNow) Descriptor() ([]byte, []int) {
	return file_antimage_v1_control_proto_rawDescGZIP(), []int{23}
}

type UpgradeRequired struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	PanelProtocolVersion uint32                 `protobuf:"varint,1,opt,name=panel_protocol_version,json=panelProtocolVersion,proto3" json:"panel_protocol_version,omitempty"`
	DownloadUrl          string                 `protobuf:"bytes,2,opt,name=download_url,json=downloadUrl,proto3" json:"download_url,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *UpgradeRequired) Reset() {
	*x = UpgradeRequired{}
	mi := &file_antimage_v1_control_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpgradeRequired) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpgradeRequired) ProtoMessage() {}

func (x *UpgradeRequired) ProtoReflect() protoreflect.Message {
	mi := &file_antimage_v1_control_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpgradeRequired.ProtoReflect.Descriptor instead.
func (*UpgradeRequired) Descriptor() ([]byte, []int) {
	return file_antimage_v1_control_proto_rawDescGZIP(), []int{24}
}

func (x *UpgradeRequired) GetPanelProtocolVersion() uint32 {
	if x != nil {
		return x.PanelProtocolVersion
	}
	return 0
}

func (x *UpgradeRequired) GetDownloadUrl() string {
	if x != nil {
		return x.DownloadUrl
	}
	return ""
}

type SnapshotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        int64                  `protobuf:"varint,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnapshotRequest) Reset() {
	*x = SnapshotRequest{}
	mi := &file_antimage_v1_control_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotRequest) ProtoMessage() {}

func (x *SnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_antimage_v1_control_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotRequest.ProtoReflect.Descriptor instead.
func (*SnapshotRequest) Descriptor() ([]byte, []int) {
	return file_antimage_v1_control_proto_rawDescGZIP(), []int{25}
}

func (x *SnapshotRequest) GetNodeId() int64 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

type SnapshotResponse struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Revision int64                  `protobuf:"varint,1,opt,name=revision,proto3" json:"revision,omitempty"`
	// Exact canonical bytes. The agent re-hashes these before applying, so this
	// must stay `bytes` rather than a structured message that could re-encode.
	Document      []byte `protobuf:"bytes,2,opt,name=document,proto3" json:"document,omitempty"`
	Sha256        string `protobuf:"bytes,3,opt,name=sha256,proto3" json:"sha256,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnapshotResponse) Reset() {
	*x = SnapshotResponse{}
	mi := &file_antimage_v1_control_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotResponse) ProtoMessage() {}

func (x *SnapshotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_antimage_v1_control_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotResponse.ProtoReflect.Descriptor instead.
func (*SnapshotResponse) Descriptor() ([]byte, []int) {
	return file_antimage_v1_control_proto_rawDescGZIP(), []int{26}
}

func (x *SnapshotResponse) GetRevision() int64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

func (x *SnapshotResponse) GetDocument() []byte {
	if x != nil {
		return x.Document
	}
	return nil
}

func (x *SnapshotResponse) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

// UsageReport carries accounting deltas from one node. SP3 design decision 1:
// the agent computes deltas; the panel never reasons about raw counters.
type UsageReport struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	NodeId int64                  `protobuf:"varint,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	// Monotonic per node. Idempotency key: (node_id, sequence).
	Sequence      int64          `protobuf:"varint,2,opt,name=sequence,proto3" json:"sequence,omitempty"`
	Samples       []*UsageSample `protobuf:"bytes,3,rep,name=samples,proto3" json:"samples,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UsageReport) Reset() {
	*x = UsageReport{}
	mi := &file_antimage_v1_control_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UsageReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsageReport) ProtoMessage() {}

func (x *UsageReport) ProtoReflect() protoreflect.Message {
	mi := &file_antimage_v1_control_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsageReport.ProtoReflect.Descriptor instead.
func (*UsageReport) Descriptor() ([]byte, []int) {
	return file_antimage_v1_control_proto_rawDescGZIP(), []int{27}
}

func (x *UsageReport) GetNodeId() int64 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

func (x *UsageReport) GetSequence() int64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *UsageReport) GetSamples() []*UsageSample {
	if x != nil {
		return x.Samples
	}
	return nil
}

// UsageSample is one subject's traffic delta on one service since the last
// report.
type UsageSample struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SubjectId     int64                  `protobuf:"varint,1,opt,name=subject_id,json=subjectId,proto3" json:"subject_id,omitempty"`
	UplinkBytes   uint64                 `protobuf:"varint,2,opt,name=uplink_bytes,json=uplinkBytes,proto3" json:"uplink_bytes,omitempty"`
	DownlinkBytes uint64                 `protobuf:"varint,3,opt,name=downlink_bytes,json=downlinkBytes,proto3" json:"downlink_bytes,omitempty"`
	// Which service the traffic went through, when the adapter can attribute it
	// (C2). Zero means "not attributed", which the panel stores as NULL rather
	// than guessing: a node running one adapter that cannot attribute, or an
	// agent older than this field, both send zero and must keep accounting.
	//
	// Deliberately not optional. Proto3 scalar presence would distinguish "the
	// agent said zero" from "the agent said nothing", and there is nothing the
	// panel would do differently: both mean the same NULL.
	ServiceId     int64 `protobuf:"varint,4,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UsageSample) Reset() {
	*x = UsageSample{}
	mi := &file_antimage_v1_control_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UsageSample) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsageSample) ProtoMessage() {}

func (x *UsageSample) ProtoReflect() protoreflect.Message {
	mi := &file_antimage_v1_control_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsageSample.ProtoReflect.Descriptor instead.
func (*UsageSample) Descriptor() ([]byte, []int) {
	return file_antimage_v1_control_proto_rawDescGZIP(), []int{28}
}

func (x *UsageSample) GetSubjectId() int64 {
	if x != nil {
		return x.SubjectId
	}
	return 0
}

func (x *UsageSample) GetUplinkBytes() uint64 {
	if x != nil {
		return x.UplinkBytes
	}
	return 0
}

func (x *UsageSample) GetDownlinkBytes() uint64 {
	if x != nil {
		return x.DownlinkBytes
	}
	return 0
}

func (x *UsageSample) GetServiceId() int64 {
	if x != nil {
		return x.ServiceId
	}
	return 0
}

var File_antimage_v1_control_proto protoreflect.FileDescriptor

const file_antimage_v1_control_proto_rawDesc = "" +
	"\n" +
	"\x19antimage/v1/control.proto\x12\vantimage.v1\"\x8e\x01\n" +
	"\rEnrollRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x17\n" +
	"\acsr_der\x18\x02 \x01(\fR\x06csrDer\x12#\n" +
	"\ragent_version\x18\x03 \x01(\tR\fagentVersion\x12)\n" +
	"\x10protocol_version\x18\x04 \x01(\rR\x0fprotocolVersion\"[\n" +
	"\x0eEnrollResponse\x12\x19\n" +
	"\bcert_der\x18\x01 \x01(\fR\acertDer\x12\x15\n" +
	"\x06ca_der\x18\x02 \x01(\fR\x05caDer\x12\x17\n" +
	"\anode_id\x18\x03 \x01(\x03R\x06nodeId\"\xc5\x02\n" +
	"\fAgentMessage\x12*\n" +
	"\x05hello\x18\x01 \x01(\v2\x12.antimage.v1.HelloH\x00R\x05hello\x126\n" +
	"\theartbeat\x18\x02 \x01(\v2\x16.antimage.v1.HeartbeatH\x00R\theartbeat\x12=\n" +
	"\fapply_report\x18\x03 \x01(\v2\x18.antimage.v1.ApplyReportH\x00R\vapplyReport\x12=\n" +
	"\fusage_report\x18\x04 \x01(\v2\x18.antimage.v1.UsageReportH\x00R\vusageReport\x12H\n" +
	"\x0ecommand_result\x18\x05 \x01(\v2\x1f.antimage.v1.AgentCommandResultH\x00R\rcommandResultB\t\n" +
	"\apayload\"\x93\x02\n" +
	"\fPanelMessage\x12@\n" +
	"\rrevision_bump\x18\x01 \x01(\v2\x19.antimage.v1.RevisionBumpH\x00R\frevisionBump\x124\n" +
	"\tfetch_now\x18\x02 \x01(\v2\x15.antimage.v1.FetchNowH\x00R\bfetchNow\x12I\n" +
	"\x10upgrade_required\x18\x03 \x01(\v2\x1c.antimage.v1.UpgradeRequiredH\x00R\x0fupgradeRequired\x125\n" +
	"\acommand\x18\x04 \x01(\v2\x19.antimage.v1.AgentCommandH\x00R\acommandB\t\n" +
	"\apayload\"\xbe\x02\n" +
	"\fAgentCommand\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x12I\n" +
	"\x10restart_adapters\x18\x02 \x01(\v2\x1c.antimage.v1.RestartAdaptersH\x00R\x0frestartAdapters\x12D\n" +
	"\x0fupdate_geo_data\x18\x03 \x01(\v2\x1a.antimage.v1.UpdateGeoDataH\x00R\rupdateGeoData\x12=\n" +
	"\fupgrade_core\x18\x04 \x01(\v2\x18.antimage.v1.UpgradeCoreH\x00R\vupgradeCore\x127\n" +
	"\n" +
	"fetch_logs\x18\x05 \x01(\v2\x16.antimage.v1.FetchLogsH\x00R\tfetchLogsB\x06\n" +
	"\x04body\"'\n" +
	"\x0fRestartAdapters\x12\x14\n" +
	"\x05kinds\x18\x01 \x03(\tR\x05kinds\"\xa5\x01\n" +
	"\rUpdateGeoData\x12\x1b\n" +
	"\tgeoip_url\x18\x01 \x01(\tR\bgeoipUrl\x12(\n" +
	"\x10geoip_sha256_url\x18\x02 \x01(\tR\x0egeoipSha256Url\x12\x1f\n" +
	"\vgeosite_url\x18\x03 \x01(\tR\n" +
	"geositeUrl\x12,\n" +
	"\x12geosite_sha256_url\x18\x04 \x01(\tR\x10geositeSha256Url\"\x90\x01\n" +
	"\vUpgradeCore\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x1d\n" +
	"\n" +
	"binary_url\x18\x02 \x01(\tR\tbinaryUrl\x12#\n" +
	"\rbinary_sha256\x18\x03 \x01(\tR\fbinarySha256\x12)\n" +
	"\x10expected_version\x18\x04 \x01(\tR\x0fexpectedVersion\"\xdc\x02\n" +
	"\x12AgentCommandResult\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x12O\n" +
	"\x10restart_adapters\x18\x02 \x01(\v2\".antimage.v1.RestartAdaptersResultH\x00R\x0frestartAdapters\x12J\n" +
	"\x0fupdate_geo_data\x18\x03 \x01(\v2 .antimage.v1.UpdateGeoDataResultH\x00R\rupdateGeoData\x12C\n" +
	"\fupgrade_core\x18\x04 \x01(\v2\x1e.antimage.v1.UpgradeCoreResultH\x00R\vupgradeCore\x12=\n" +
	"\n" +
	"fetch_logs\x18\x05 \x01(\v2\x1c.antimage.v1.FetchLogsResultH\x00R\tfetchLogsB\x06\n" +
	"\x04body\"5\n" +
	"\tFetchLogs\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x14\n" +
	"\x05lines\x18\x02 \x01(\x05R\x05lines\"_\n" +
	"\x0fFetchLogsResult\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x0e\n" +
	"\x02ok\x18\x02 \x01(\bR\x02ok\x12\x12\n" +
	"\x04logs\x18\x03 \x01(\tR\x04logs\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"\x9b\x01\n" +
	"\x11UpgradeCoreResult\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x0e\n" +
	"\x02ok\x18\x02 \x01(\bR\x02ok\x12+\n" +
	"\x11installed_version\x18\x03 \x01(\tR\x10installedVersion\x12\x1f\n" +
	"\vrolled_back\x18\x04 \x01(\bR\n" +
	"rolledBack\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error\"W\n" +
	"\x13UpdateGeoDataResult\x12@\n" +
	"\boutcomes\x18\x01 \x03(\v2$.antimage.v1.AdapterGeoUpdateOutcomeR\boutcomes\"\x9d\x01\n" +
	"\x17AdapterGeoUpdateOutcome\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x0e\n" +
	"\x02ok\x18\x02 \x01(\bR\x02ok\x12!\n" +
	"\fgeoip_sha256\x18\x03 \x01(\tR\vgeoipSha256\x12%\n" +
	"\x0egeosite_sha256\x18\x04 \x01(\tR\rgeositeSha256\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error\"W\n" +
	"\x15RestartAdaptersResult\x12>\n" +
	"\boutcomes\x18\x01 \x03(\v2\".antimage.v1.AdapterRestartOutcomeR\boutcomes\"Q\n" +
	"\x15AdapterRestartOutcome\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x0e\n" +
	"\x02ok\x18\x02 \x01(\bR\x02ok\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"\xf6\x01\n" +
	"\x05Hello\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\x03R\x06nodeId\x12#\n" +
	"\ragent_version\x18\x02 \x01(\tR\fagentVersion\x12)\n" +
	"\x10protocol_version\x18\x03 \x01(\rR\x0fprotocolVersion\x12)\n" +
	"\x10applied_revision\x18\x04 \x01(\x03R\x0fappliedRevision\x12\x1d\n" +
	"\n" +
	"doc_sha256\x18\x05 \x01(\tR\tdocSha256\x12:\n" +
	"\badapters\x18\x06 \x03(\v2\x1e.antimage.v1.AdapterDescriptorR\badapters\"\xfa\x01\n" +
	"\x11AdapterDescriptor\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12 \n" +
	"\fhot_user_add\x18\x03 \x01(\bR\n" +
	"hotUserAdd\x12'\n" +
	"\x0fself_accounting\x18\x04 \x01(\bR\x0eselfAccounting\x12!\n" +
	"\frequires_pki\x18\x05 \x01(\bR\vrequiresPki\x12%\n" +
	"\x0eservice_schema\x18\x06 \x01(\fR\rserviceSchema\x12\"\n" +
	"\fcapabilities\x18\a \x03(\tR\fcapabilities\"\xb1\x01\n" +
	"\tHeartbeat\x12\x14\n" +
	"\x05load1\x18\x01 \x01(\x01R\x05load1\x12$\n" +
	"\x0emem_used_bytes\x18\x02 \x01(\x04R\fmemUsedBytes\x12%\n" +
	"\x0euptime_seconds\x18\x03 \x01(\x04R\ruptimeSeconds\x12A\n" +
	"\x0eadapter_health\x18\x04 \x03(\v2\x1a.antimage.v1.AdapterHealthR\radapterHealth\"K\n" +
	"\rAdapterHealth\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x0e\n" +
	"\x02ok\x18\x02 \x01(\bR\x02ok\x12\x16\n" +
	"\x06detail\x18\x03 \x01(\tR\x06detail\"\xd4\x01\n" +
	"\vApplyReport\x12'\n" +
	"\x0ftarget_revision\x18\x01 \x01(\x03R\x0etargetRevision\x12\x1c\n" +
	"\tconverged\x18\x02 \x01(\bR\tconverged\x12\x1a\n" +
	"\bdeferred\x18\x03 \x01(\bR\bdeferred\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\x12\x1d\n" +
	"\n" +
	"doc_sha256\x18\x05 \x01(\tR\tdocSha256\x12-\n" +
	"\x05steps\x18\x06 \x03(\v2\x17.antimage.v1.StepResultR\x05steps\"\x99\x01\n" +
	"\n" +
	"StepResult\x12\x10\n" +
	"\x03seq\x18\x01 \x01(\x05R\x03seq\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\x12\x1e\n" +
	"\n" +
	"disruption\x18\x03 \x01(\tR\n" +
	"disruption\x12\x0e\n" +
	"\x02ok\x18\x04 \x01(\bR\x02ok\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error\x12\x1f\n" +
	"\vduration_ms\x18\x06 \x01(\x03R\n" +
	"durationMs\"*\n" +
	"\fRevisionBump\x12\x1a\n" +
	"\brevision\x18\x01 \x01(\x03R\brevision\"\n" +
	"\n" +
	"\bFetchNow\"j\n" +
	"\x0fUpgradeRequired\x124\n" +
	"\x16panel_protocol_version\x18\x01 \x01(\rR\x14panelProtocolVersion\x12!\n" +
	"\fdownload_url\x18\x02 \x01(\tR\vdownloadUrl\"*\n" +
	"\x0fSnapshotRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\x03R\x06nodeId\"b\n" +
	"\x10SnapshotResponse\x12\x1a\n" +
	"\brevision\x18\x01 \x01(\x03R\brevision\x12\x1a\n" +
	"\bdocument\x18\x02 \x01(\fR\bdocument\x12\x16\n" +
	"\x06sha256\x18\x03 \x01(\tR\x06sha256\"v\n" +
	"\vUsageReport\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\x03R\x06nodeId\x12\x1a\n" +
	"\bsequence\x18\x02 \x01(\x03R\bsequence\x122\n" +
	"\asamples\x18\x03 \x03(\v2\x18.antimage.v1.UsageSampleR\asamples\"\x95\x01\n" +
	"\vUsageSample\x12\x1d\n" +
	"\n" +
	"subject_id\x18\x01 \x01(\x03R\tsubjectId\x12!\n" +
	"\fuplink_bytes\x18\x02 \x01(\x04R\vuplinkBytes\x12%\n" +
	"\x0edownlink_bytes\x18\x03 \x01(\x04R\rdownlinkBytes\x12\x1d\n" +
	"\n" +
	"service_id\x18\x04 \x01(\x03R\tserviceId2O\n" +
	"\n" +
	"Enrollment\x12A\n" +
	"\x06Enroll\x12\x1a.antimage.v1.EnrollRequest\x1a\x1b.antimage.v1.EnrollResponse2\xa0\x01\n" +
	"\aControl\x12B\n" +
	"\x06Stream\x12\x19.antimage.v1.AgentMessage\x1a\x19.antimage.v1.PanelMessage(\x010\x01\x12Q\n" +
	"\x12GetDesiredSnapshot\x12\x1c.antimage.v1.SnapshotRequest\x1a\x1d.antimage.v1.SnapshotResponseBHZFgithub.com/amyrm/antimage/internal/shared/proto/antimage/v1;antimagev1b\x06proto3"

var (
	file_antimage_v1_control_proto_rawDescOnce sync.Once
	file_antimage_v1_control_proto_rawDescData []byte
)

func file_antimage_v1_control_proto_rawDescGZIP() []byte {
	file_antimage_v1_control_proto_rawDescOnce.Do(func() {
		file_antimage_v1_control_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_antimage_v1_control_proto_rawDesc), len(file_antimage_v1_control_proto_rawDesc)))
	})
	return file_antimage_v1_control_proto_rawDescData
}

var file_antimage_v1_control_proto_msgTypes = make([]protoimpl.MessageInfo, 29)
var file_antimage_v1_control_proto_goTypes = []any{
	(*EnrollRequest)(nil),           // 0: antimage.v1.EnrollRequest
	(*EnrollResponse)(nil),          // 1: antimage.v1.EnrollResponse
	(*AgentMessage)(nil),            // 2: antimage.v1.AgentMessage
	(*PanelMessage)(nil),            // 3: antimage.v1.PanelMessage
	(*AgentCommand)(nil),            // 4: antimage.v1.AgentCommand
	(*RestartAdapters)(nil),         // 5: antimage.v1.RestartAdapters
	(*UpdateGeoData)(nil),           // 6: antimage.v1.UpdateGeoData
	(*UpgradeCore)(nil),             // 7: antimage.v1.UpgradeCore
	(*AgentCommandResult)(nil),      // 8: antimage.v1.AgentCommandResult
	(*FetchLogs)(nil),               // 9: antimage.v1.FetchLogs
	(*FetchLogsResult)(nil),         // 10: antimage.v1.FetchLogsResult
	(*UpgradeCoreResult)(nil),       // 11: antimage.v1.UpgradeCoreResult
	(*UpdateGeoDataResult)(nil),     // 12: antimage.v1.UpdateGeoDataResult
	(*AdapterGeoUpdateOutcome)(nil), // 13: antimage.v1.AdapterGeoUpdateOutcome
	(*RestartAdaptersResult)(nil),   // 14: antimage.v1.RestartAdaptersResult
	(*AdapterRestartOutcome)(nil),   // 15: antimage.v1.AdapterRestartOutcome
	(*Hello)(nil),                   // 16: antimage.v1.Hello
	(*AdapterDescriptor)(nil),       // 17: antimage.v1.AdapterDescriptor
	(*Heartbeat)(nil),               // 18: antimage.v1.Heartbeat
	(*AdapterHealth)(nil),           // 19: antimage.v1.AdapterHealth
	(*ApplyReport)(nil),             // 20: antimage.v1.ApplyReport
	(*StepResult)(nil),              // 21: antimage.v1.StepResult
	(*RevisionBump)(nil),            // 22: antimage.v1.RevisionBump
	(*FetchNow)(nil),                // 23: antimage.v1.FetchNow
	(*UpgradeRequired)(nil),         // 24: antimage.v1.UpgradeRequired
	(*SnapshotRequest)(nil),         // 25: antimage.v1.SnapshotRequest
	(*SnapshotResponse)(nil),        // 26: antimage.v1.SnapshotResponse
	(*UsageReport)(nil),             // 27: antimage.v1.UsageReport
	(*UsageSample)(nil),             // 28: antimage.v1.UsageSample
}
var file_antimage_v1_control_proto_depIdxs = []int32{
	16, // 0: antimage.v1.AgentMessage.hello:type_name -> antimage.v1.Hello
	18, // 1: antimage.v1.AgentMessage.heartbeat:type_name -> antimage.v1.Heartbeat
	20, // 2: antimage.v1.AgentMessage.apply_report:type_name -> antimage.v1.ApplyReport
	27, // 3: antimage.v1.AgentMessage.usage_report:type_name -> antimage.v1.UsageReport
	8,  // 4: antimage.v1.AgentMessage.command_result:type_name -> antimage.v1.AgentCommandResult
	22, // 5: antimage.v1.PanelMessage.revision_bump:type_name -> antimage.v1.RevisionBump
	23, // 6: antimage.v1.PanelMessage.fetch_now:type_name -> antimage.v1.FetchNow
	24, // 7: antimage.v1.PanelMessage.upgrade_required:type_name -> antimage.v1.UpgradeRequired
	4,  // 8: antimage.v1.PanelMessage.command:type_name -> antimage.v1.AgentCommand
	5,  // 9: antimage.v1.AgentCommand.restart_adapters:type_name -> antimage.v1.RestartAdapters
	6,  // 10: antimage.v1.AgentCommand.update_geo_data:type_name -> antimage.v1.UpdateGeoData
	7,  // 11: antimage.v1.AgentCommand.upgrade_core:type_name -> antimage.v1.UpgradeCore
	9,  // 12: antimage.v1.AgentCommand.fetch_logs:type_name -> antimage.v1.FetchLogs
	14, // 13: antimage.v1.AgentCommandResult.restart_adapters:type_name -> antimage.v1.RestartAdaptersResult
	12, // 14: antimage.v1.AgentCommandResult.update_geo_data:type_name -> antimage.v1.UpdateGeoDataResult
	11, // 15: antimage.v1.AgentCommandResult.upgrade_core:type_name -> antimage.v1.UpgradeCoreResult
	10, // 16: antimage.v1.AgentCommandResult.fetch_logs:type_name -> antimage.v1.FetchLogsResult
	13, // 17: antimage.v1.UpdateGeoDataResult.outcomes:type_name -> antimage.v1.AdapterGeoUpdateOutcome
	15, // 18: antimage.v1.RestartAdaptersResult.outcomes:type_name -> antimage.v1.AdapterRestartOutcome
	17, // 19: antimage.v1.Hello.adapters:type_name -> antimage.v1.AdapterDescriptor
	19, // 20: antimage.v1.Heartbeat.adapter_health:type_name -> antimage.v1.AdapterHealth
	21, // 21: antimage.v1.ApplyReport.steps:type_name -> antimage.v1.StepResult
	28, // 22: antimage.v1.UsageReport.samples:type_name -> antimage.v1.UsageSample
	0,  // 23: antimage.v1.Enrollment.Enroll:input_type -> antimage.v1.EnrollRequest
	2,  // 24: antimage.v1.Control.Stream:input_type -> antimage.v1.AgentMessage
	25, // 25: antimage.v1.Control.GetDesiredSnapshot:input_type -> antimage.v1.SnapshotRequest
	1,  // 26: antimage.v1.Enrollment.Enroll:output_type -> antimage.v1.EnrollResponse
	3,  // 27: antimage.v1.Control.Stream:output_type -> antimage.v1.PanelMessage
	26, // 28: antimage.v1.Control.GetDesiredSnapshot:output_type -> antimage.v1.SnapshotResponse
	26, // [26:29] is the sub-list for method output_type
	23, // [23:26] is the sub-list for method input_type
	23, // [23:23] is the sub-list for extension type_name
	23, // [23:23] is the sub-list for extension extendee
	0,  // [0:23] is the sub-list for field type_name
}

func init() { file_antimage_v1_control_proto_init() }
func file_antimage_v1_control_proto_init() {
	if File_antimage_v1_control_proto != nil {
		return
	}
	file_antimage_v1_control_proto_msgTypes[2].OneofWrappers = []any{
		(*AgentMessage_Hello)(nil),
		(*AgentMessage_Heartbeat)(nil),
		(*AgentMessage_ApplyReport)(nil),
		(*AgentMessage_UsageReport)(nil),
		(*AgentMessage_CommandResult)(nil),
	}
	file_antimage_v1_control_proto_msgTypes[3].OneofWrappers = []any{
		(*PanelMessage_RevisionBump)(nil),
		(*PanelMessage_FetchNow)(nil),
		(*PanelMessage_UpgradeRequired)(nil),
		(*PanelMessage_Command)(nil),
	}
	file_antimage_v1_control_proto_msgTypes[4].OneofWrappers = []any{
		(*AgentCommand_RestartAdapters)(nil),
		(*AgentCommand_UpdateGeoData)(nil),
		(*AgentCommand_UpgradeCore)(nil),
		(*AgentCommand_FetchLogs)(nil),
	}
	file_antimage_v1_control_proto_msgTypes[8].OneofWrappers = []any{
		(*AgentCommandResult_RestartAdapters)(nil),
		(*AgentCommandResult_UpdateGeoData)(nil),
		(*AgentCommandResult_UpgradeCore)(nil),
		(*AgentCommandResult_FetchLogs)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_antimage_v1_control_proto_rawDesc), len(file_antimage_v1_control_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   29,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_antimage_v1_control_proto_goTypes,
		DependencyIndexes: file_antimage_v1_control_proto_depIdxs,
		MessageInfos:      file_antimage_v1_control_proto_msgTypes,
	}.Build()
	File_antimage_v1_control_proto = out.File
	file_antimage_v1_control_proto_goTypes = nil
	file_antimage_v1_control_proto_depIdxs = nil
}
