package nodeagent

import (
	"encoding/base64"
	"fmt"
	"strconv"
	"strings"
)

// xrayUserIdentity represents a parsed Xray user identity from the email field
type xrayUserIdentity struct {
	UserID     int64
	Username   string
	InboundTag string
}

// parseXrayUserEmail parses the runtime user email generated by inboundRuntimeUserEmail.
// Format: "userID.rb1_<base64(tag)>.username" or legacy "userID.username"
// Returns the user identity or an error if the format is invalid.
func parseXrayUserEmail(email string) (xrayUserIdentity, error) {
	email = strings.TrimSpace(email)
	if email == "" {
		return xrayUserIdentity{}, fmt.Errorf("empty email")
	}

	// Split by dots
	parts := strings.Split(email, ".")
	if len(parts) < 2 {
		return xrayUserIdentity{}, fmt.Errorf("invalid email format: %q", email)
	}

	// First part must be user ID
	userIDStr := strings.TrimSpace(parts[0])
	userID, err := strconv.ParseInt(userIDStr, 10, 64)
	if err != nil || userID <= 0 {
		return xrayUserIdentity{}, fmt.Errorf("invalid user ID in email %q: %w", email, err)
	}

	// Check if this is the new tagged format: userID.rb1_<encodedTag>.username
	if len(parts) >= 3 && strings.HasPrefix(parts[1], "rb1_") {
		encodedTag := strings.TrimPrefix(parts[1], "rb1_")
		tagBytes, err := base64.RawURLEncoding.DecodeString(encodedTag)
		if err != nil {
			return xrayUserIdentity{}, fmt.Errorf("invalid tag encoding in email %q: %w", email, err)
		}

		tag := string(tagBytes)
		if strings.TrimSpace(tag) == "" {
			return xrayUserIdentity{}, fmt.Errorf("decoded tag is empty in email %q", email)
		}

		// Username is the remaining parts joined
		username := strings.Join(parts[2:], ".")

		return xrayUserIdentity{
			UserID:     userID,
			Username:   username,
			InboundTag: tag,
		}, nil
	}

	// Legacy format: userID.username
	username := strings.Join(parts[1:], ".")

	return xrayUserIdentity{
		UserID:     userID,
		Username:   username,
		InboundTag: "",
	}, nil
}

// xrayStatName represents a parsed Xray stat name
type xrayStatName struct {
	Type      string // "user", "outbound", "inbound"
	Email     string // For user stats
	Tag       string // For outbound/inbound stats
	Metric    string // "traffic", "online"
	Direction string // "uplink", "downlink" (for traffic only)
}

// parseXrayStatName parses Xray stat names such as:
// - "user>>>email>>>traffic>>>uplink"
// - "user>>>email>>>traffic>>>downlink"
// - "user>>>email>>>online"
// - "outbound>>>tag>>>traffic>>>uplink"
// - "outbound>>>tag>>>traffic>>>downlink"
// - "inbound>>>tag>>>traffic>>>uplink"
// - "inbound>>>tag>>>traffic>>>downlink"
func parseXrayStatName(name string) (xrayStatName, bool) {
	parts := strings.Split(name, ">>>")
	if len(parts) < 3 {
		return xrayStatName{}, false
	}

	statType := strings.ToLower(strings.TrimSpace(parts[0]))
	identity := strings.TrimSpace(parts[1])
	metric := strings.ToLower(strings.TrimSpace(parts[2]))

	switch statType {
	case "user":
		if identity == "" {
			return xrayStatName{}, false
		}

		if metric == "online" {
			// user>>>email>>>online
			return xrayStatName{
				Type:   "user",
				Email:  identity,
				Metric: "online",
			}, true
		}

		if metric == "traffic" {
			// user>>>email>>>traffic>>>uplink|downlink
			if len(parts) != 4 {
				return xrayStatName{}, false
			}
			direction := strings.ToLower(strings.TrimSpace(parts[3]))
			if direction != "uplink" && direction != "downlink" {
				return xrayStatName{}, false
			}
			return xrayStatName{
				Type:      "user",
				Email:     identity,
				Metric:    "traffic",
				Direction: direction,
			}, true
		}

		return xrayStatName{}, false

	case "outbound", "inbound":
		if identity == "" || metric != "traffic" {
			return xrayStatName{}, false
		}
		if len(parts) != 4 {
			return xrayStatName{}, false
		}
		direction := strings.ToLower(strings.TrimSpace(parts[3]))
		if direction != "uplink" && direction != "downlink" {
			return xrayStatName{}, false
		}
		return xrayStatName{
			Type:      statType,
			Tag:       identity,
			Metric:    "traffic",
			Direction: direction,
		}, true

	default:
		return xrayStatName{}, false
	}
}
