package nodeagent

import (
	"encoding/base64"
	"fmt"
	"strconv"
	"strings"
)

// xrayUserIdentity represents a parsed Xray user identity from the email field
type xrayUserIdentity struct {
	UserID     int64
	Username   string
	InboundTag string
}

// parseXrayUserEmail parses the runtime user email generated by inboundRuntimeUserEmail.
// Format: "userID.rb1_<base64(tag)>.username" or legacy "userID.username"
// Returns the user identity or an error if the format is invalid.
func parseXrayUserEmail(email string) (xrayUserIdentity, error) {
	email = strings.TrimSpace(email)
	if email == "" {
		return xrayUserIdentity{}, fmt.Errorf("empty email")
	}

	// Split by dots
	parts := strings.Split(email, ".")
	if len(parts) < 2 {
		return xrayUserIdentity{}, fmt.Errorf("invalid email format: %q", email)
	}

	// First part must be user ID
	userIDStr := strings.TrimSpace(parts[0])
	userID, err := strconv.ParseInt(userIDStr, 10, 64)
	if err != nil || userID <= 0 {
		return xrayUserIdentity{}, fmt.Errorf("invalid user ID in email %q: %w", email, err)
	}

	// Check if this is the new tagged format: userID.rb1_<encodedTag>.username
	if len(parts) >= 3 && strings.HasPrefix(parts[1], "rb1_") {
		encodedTag := strings.TrimPrefix(parts[1], "rb1_")
		tagBytes, err := base64.RawURLEncoding.DecodeString(encodedTag)
		if err != nil {
			return xrayUserIdentity{}, fmt.Errorf("invalid tag encoding in email %q: %w", email, err)
		}

		tag := string(tagBytes)
		if strings.TrimSpace(tag) == "" {
			return xrayUserIdentity{}, fmt.Errorf("decoded tag is empty in email %q", email)
		}

		// Username is the remaining parts joined
		username := strings.Join(parts[2:], ".")

		return xrayUserIdentity{
			UserID:     userID,
			Username:   username,
			InboundTag: tag,
		}, nil
	}

	// Legacy format: userID.username
	username := strings.Join(parts[1:], ".")

	return xrayUserIdentity{
		UserID:     userID,
		Username:   username,
		InboundTag: "",
	}, nil
}

// xrayStatName represents a parsed Xray stat name
type xrayStatName struct {
	Type      string // "user" or "outbound" or "inbound"
	Email     string // for user stats
	Tag       string // for outbound/inbound stats
	Direction string // "uplink" or "downlink"
}

// parseXrayStatName parses Xray stat names such as:
// - "user>>>email>>>traffic>>>uplink"
// - "user>>>email>>>traffic>>>downlink"
// - "outbound>>>tag>>>traffic>>>uplink"
// - "outbound>>>tag>>>traffic>>>downlink"
// - "inbound>>>tag>>>traffic>>>uplink"
// - "inbound>>>tag>>>traffic>>>downlink"
func parseXrayStatName(name string) (xrayStatName, bool) {
	parts := strings.Split(name, ">>>")
	if len(parts) != 4 {
		return xrayStatName{}, false
	}

	statType := strings.ToLower(strings.TrimSpace(parts[0]))
	identity := strings.TrimSpace(parts[1])
	if parts[2] != "traffic" {
		return xrayStatName{}, false
	}

	direction := strings.ToLower(strings.TrimSpace(parts[3]))
	if direction != "uplink" && direction != "downlink" {
		return xrayStatName{}, false
	}

	switch statType {
	case "user":
		if identity == "" {
			return xrayStatName{}, false
		}
		return xrayStatName{
			Type:      "user",
			Email:     identity,
			Direction: direction,
		}, true

	case "outbound":
		if identity == "" {
			return xrayStatName{}, false
		}
		return xrayStatName{
			Type:      "outbound",
			Tag:       identity,
			Direction: direction,
		}, true

	case "inbound":
		if identity == "" {
			return xrayStatName{}, false
		}
		return xrayStatName{
			Type:      "inbound",
			Tag:       identity,
			Direction: direction,
		}, true

	default:
		return xrayStatName{}, false
	}
}
